"""This file was generated by xsdata, v24.11, on 2026-08-22 11:29:33

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import Optional

from nfelib import CommonMixin

__NAMESPACE__ = (
    "http://www.reinf.esocial.gov.br/schemas/evtReabreEvPer/v2_01_02"
)


@dataclass
class Reinf(CommonMixin):
    """
    Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais (EFD-
    Reinf)
    "

    :ivar evtReabreEvPer: Evento de reabertura de eventos periodicos
    :ivar signature:
    """

    class Meta:
        namespace = (
            "http://www.reinf.esocial.gov.br/schemas/evtReabreEvPer/v2_01_02"
        )

    evtReabreEvPer: Optional["Reinf.EvtReabreEvPer"] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    signature: Optional[str] = field(
        default=None,
        metadata={
            "name": "Signature",
            "type": "Element",
            "namespace": "http://www.w3.org/2000/09/xmldsig#",
            "required": True,
        },
    )

    @dataclass
    class EvtReabreEvPer:
        """

        "

        :ivar ideEvento: Informacoes de identificacao do evento
        :ivar ideContri: Informacoes de identificacao do contribuinte
        :ivar id: Identificacao unica do evento
        """

        ideEvento: Optional["Reinf.EvtReabreEvPer.IdeEvento"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideContri: Optional["Reinf.EvtReabreEvPer.IdeContri"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        id: Optional[str] = field(
            default=None,
            metadata={
                "type": "Attribute",
                "required": True,
                "length": 36,
                "pattern": r"I{1}D{1}[0-9]{1}[0-9A-Z]{12}[0-9]{21}",
            },
        )

        @dataclass
        class IdeEvento:
            """

            "

            :ivar perApur: Periodo de apuracao
            :ivar tpAmb: Tipo de ambiente
            :ivar procEmi: Processo de emissao do evento
            :ivar verProc: Versao do processo de emissao do evento.
            """

            perApur: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"20([1-9][0-9])-(0[1-9]|1[0-2])",
                },
            )
            tpAmb: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            procEmi: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            verProc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 1,
                    "max_length": 20,
                },
            )

        @dataclass
        class IdeContri:
            """

            "

            :ivar tpInsc: Tipo de Inscricao
            :ivar nrInsc: Numero de Inscricao
            """

            tpInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            nrInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[0-9A-Z]{8}|[0-9]{11}|[0-9A-Z]{14}",
                },
            )
