"""This file was generated by xsdata, v24.11, on 2026-08-22 11:29:33

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import List, Optional

from nfelib import CommonMixin

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evt4020PagtoBeneficiarioPJ/v2_01_02"


@dataclass
class Reinf(CommonMixin):
    """
    Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais (EFD-
    Reinf)
    "

    :ivar evtRetPJ: Evento retencoes na fonte PJ
    :ivar signature:
    """

    class Meta:
        namespace = "http://www.reinf.esocial.gov.br/schemas/evt4020PagtoBeneficiarioPJ/v2_01_02"

    evtRetPJ: Optional["Reinf.EvtRetPj"] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    signature: Optional[str] = field(
        default=None,
        metadata={
            "name": "Signature",
            "type": "Element",
            "namespace": "http://www.w3.org/2000/09/xmldsig#",
            "required": True,
        },
    )

    @dataclass
    class EvtRetPj:
        """

        "

        :ivar ideEvento: Informacoes de identificacao do evento
        :ivar ideContri: Informacoes de identificacao do contribuinte
        :ivar ideEstab: Informacoes de identificacao do estabelecimento
        :ivar id: Identificacao unica do evento
        """

        ideEvento: Optional["Reinf.EvtRetPj.IdeEvento"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideContri: Optional["Reinf.EvtRetPj.IdeContri"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideEstab: Optional["Reinf.EvtRetPj.IdeEstab"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        id: Optional[str] = field(
            default=None,
            metadata={
                "type": "Attribute",
                "required": True,
                "length": 36,
                "pattern": r"I{1}D{1}[0-9]{1}[0-9A-Z]{12}[0-9]{21}",
            },
        )

        @dataclass
        class IdeEvento:
            """

            "

            :ivar indRetif: Indicativo de Retificacao
            :ivar nrRecibo: Recibo arquivo a ser retificado
            :ivar perApur: Periodo de apuracao
            :ivar tpAmb: Tipo de ambiente
            :ivar procEmi: Processo de emissao do evento
            :ivar verProc: Versao do processo de emissao do evento.
            """

            indRetif: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            nrRecibo: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "max_length": 52,
                    "pattern": r"[0-9]{1,18}[-][0-9]{2}[-][0-9]{4}[-][0-9]{4}[-][0-9]{1,18}",
                },
            )
            perApur: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"20([1-9][0-9])-(0[1-9]|1[0-2])",
                },
            )
            tpAmb: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            procEmi: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            verProc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 1,
                    "max_length": 20,
                },
            )

        @dataclass
        class IdeContri:
            """

            "

            :ivar tpInsc: Tipo de Inscricao
            :ivar nrInsc: Numero de Inscricao
            :ivar infoComplContri: Informacoes complementares do
                contribuinte
            """

            tpInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            nrInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[0-9A-Z]{8}|[0-9]{11}|[0-9A-Z]{14}",
                },
            )
            infoComplContri: Optional[
                "Reinf.EvtRetPj.IdeContri.InfoComplContri"
            ] = field(
                default=None,
                metadata={
                    "type": "Element",
                },
            )

            @dataclass
            class InfoComplContri:
                """

                "

                :ivar natJur: Natureza juridica do declarante
                """

                natJur: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{4}",
                    },
                )

        @dataclass
        class IdeEstab:
            """

            "

            :ivar tpInscEstab: Tipo de inscricao do estabelecimento
            :ivar nrInscEstab: Numero de inscricao do estabelecimento
            :ivar ideBenef: Identificacao do beneficiario do rendimento
            """

            tpInscEstab: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2|3",
                },
            )
            nrInscEstab: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[0-9]{11}|[0-9A-Z]{14}",
                },
            )
            ideBenef: Optional["Reinf.EvtRetPj.IdeEstab.IdeBenef"] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )

            @dataclass
            class IdeBenef:
                """

                "

                :ivar cnpjBenef: CNPJ do beneficiario
                :ivar nmBenef: Nome do beneficiario
                :ivar isenImun: Informacoes sobre isencao e imunidade
                :ivar ideEvtAdic: Identificador de evento adicional por
                    beneficiario, a criterio do declarante.
                :ivar idePgto: Identificacao do rendimento
                """

                cnpjBenef: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "pattern": r"[0-9A-Z]{14}",
                    },
                )
                nmBenef: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 70,
                        "white_space": "preserve",
                    },
                )
                isenImun: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "pattern": r"2|3",
                    },
                )
                ideEvtAdic: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 8,
                    },
                )
                idePgto: List["Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto"] = (
                    field(
                        default_factory=list,
                        metadata={
                            "type": "Element",
                            "min_occurs": 1,
                            "max_occurs": 100,
                        },
                    )
                )

                @dataclass
                class IdePgto:
                    """

                    "

                    :ivar natRend: Natureza do Rendimento
                    :ivar observ: Observacoes
                    :ivar infoPgto: Informacoes relativas ao pagamento
                    """

                    natRend: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "pattern": r"\d{5}",
                        },
                    )
                    observ: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "max_length": 200,
                            "white_space": "preserve",
                        },
                    )
                    infoPgto: List[
                        "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto"
                    ] = field(
                        default_factory=list,
                        metadata={
                            "type": "Element",
                            "min_occurs": 1,
                            "max_occurs": 999,
                        },
                    )

                    @dataclass
                    class InfoPgto:
                        """

                        "

                        :ivar dtFG: Data do pagamento.
                        :ivar vlrBruto: Valor bruto
                        :ivar indFciScp: Indicativo de FCI ou SCP
                        :ivar nrInscFciScp: CNPJ do FCI ou SCP
                        :ivar percSCP: Percentual de participacao na SCP
                        :ivar indJud: Indicativo de rendimento oriundo
                            de decisao judicial
                        :ivar paisResidExt: Codigo do Pais
                        :ivar dtEscrCont: Data da escrituracao contabil
                            referente ao IRRF dos juros sobre capital
                            proprio informada no evento R-4040.
                        :ivar observ: Observacoes
                        :ivar retencoes: Informacoes relativas a
                            retencoes na fonte
                        :ivar infoProcRet: Processos relacionados a nao
                            retencao de tributos
                        :ivar infoProcJud: Informacoes complementares
                            relativas a rendimentos decorrentes de
                            decisao judicial
                        :ivar infoPgtoExt: Informacoes complementares
                            relativas a pagamentos no Exterior
                        """

                        dtFG: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "required": True,
                                "pattern": r"20([1-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|1[0-9]|2[0-9]|3[0-1])",
                            },
                        )
                        vlrBruto: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "min_length": 4,
                                "max_length": 15,
                                "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                            },
                        )
                        indFciScp: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "pattern": r"1|2",
                            },
                        )
                        nrInscFciScp: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "pattern": r"[0-9A-Z]{14}",
                            },
                        )
                        percSCP: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "pattern": r"(([0-9]|[1-9][0-9])[,][0-9])|100,0",
                            },
                        )
                        indJud: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "pattern": r"S|N",
                            },
                        )
                        paisResidExt: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "pattern": r"\d{3}",
                            },
                        )
                        dtEscrCont: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "pattern": r"20[0-9]{2}-[0-1][0-9]-[0-3][0-9]",
                            },
                        )
                        observ: Optional[str] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                                "max_length": 200,
                                "white_space": "preserve",
                            },
                        )
                        retencoes: Optional[
                            "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.Retencoes"
                        ] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                            },
                        )
                        infoProcRet: List[
                            "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcRet"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "type": "Element",
                                "max_occurs": 50,
                            },
                        )
                        infoProcJud: Optional[
                            "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcJud"
                        ] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                            },
                        )
                        infoPgtoExt: Optional[
                            "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoPgtoExt"
                        ] = field(
                            default=None,
                            metadata={
                                "type": "Element",
                            },
                        )

                        @dataclass
                        class Retencoes:
                            """

                            "

                            :ivar vlrBaseIR: Valor da base do IR
                            :ivar vlrIR: Valor da retencao do IR
                            :ivar vlrBaseAgreg: Valor da base retencoes
                                agregadas
                            :ivar vlrAgreg: Valor retencao de tributos
                                em valor agregado
                            :ivar vlrBaseCSLL: Valor da base da CSLL
                            :ivar vlrCSLL: Retencao CSLL
                            :ivar vlrBaseCofins: Valor da base Cofins
                            :ivar vlrCofins: Valor Cofins
                            :ivar vlrBasePP: Valor da base do PIS/PASEP
                            :ivar vlrPP: Retencao do PIS/PASEP
                            """

                            vlrBaseIR: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrIR: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBaseAgreg: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrAgreg: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBaseCSLL: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrCSLL: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBaseCofins: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrCofins: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBasePP: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrPP: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )

                        @dataclass
                        class InfoProcRet:
                            """

                            "

                            :ivar tpProcRet: Tipo de Processo
                            :ivar nrProcRet: Numero do Processo
                            :ivar codSusp: Codigo do indicativo da
                                suspensao
                            :ivar vlrBaseSuspIR: Valor da base do IR com
                                exigibilidade suspensa
                            :ivar vlrNIR: Valor nao retido de IR
                            :ivar vlrDepIR: Valor do deposito judicial
                                de IR
                            :ivar vlrBaseSuspCSLL: Valor da base CSLL
                                suspenso
                            :ivar vlrNCSLL: Valor CSLL nao retido
                            :ivar vlrDepCSLL: Valor deposito judicial de
                                CSLL
                            :ivar vlrBaseSuspCofins: Valor da base
                                Cofins com exibilidade suspensa
                            :ivar vlrNCofins: Valor da retencao Cofins
                                que deixou de ser efetuada
                            :ivar vlrDepCofins: Valor deposito judicial
                                de Cofins
                            :ivar vlrBaseSuspPP: Valor da base do
                                PIS/PASEP com exigibilidade suspensa
                            :ivar vlrNPP: Valor do PIS/PASEP nao retido
                            :ivar vlrDepPP: Valor deposito judicial de
                                PIS/PASEP
                            """

                            tpProcRet: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "pattern": r"1|2",
                                },
                            )
                            nrProcRet: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "min_length": 1,
                                    "max_length": 21,
                                    "pattern": r"[0-9]{1,21}",
                                },
                            )
                            codSusp: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "pattern": r"[0-9]{1,14}",
                                },
                            )
                            vlrBaseSuspIR: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrNIR: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrDepIR: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBaseSuspCSLL: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrNCSLL: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrDepCSLL: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBaseSuspCofins: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrNCofins: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrDepCofins: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrBaseSuspPP: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrNPP: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )
                            vlrDepPP: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 15,
                                    "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                },
                            )

                        @dataclass
                        class InfoProcJud:
                            """

                            "

                            :ivar nrProc: Numero do Processo
                            :ivar indOrigRec: Indicativo de origem dos
                                recursos
                            :ivar cnpjOrigRecurso: CNPJ da empresa que
                                repassou os recursos
                            :ivar cpfOrigRecurso: CPF da origem dos
                                recursos
                            :ivar desc: Descricao
                            :ivar despProcJud: Despesas com processo
                                judicial
                            """

                            nrProc: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "min_length": 1,
                                    "max_length": 21,
                                },
                            )
                            indOrigRec: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "pattern": r"1|2",
                                },
                            )
                            cnpjOrigRecurso: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "pattern": r"[0-9A-Z]{14}",
                                },
                            )
                            cpfOrigRecurso: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "pattern": r"[0-9]{11}",
                                },
                            )
                            desc: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 50,
                                    "white_space": "preserve",
                                },
                            )
                            despProcJud: Optional[
                                "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcJud.DespProcJud"
                            ] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                },
                            )

                            @dataclass
                            class DespProcJud:
                                """

                                "

                                :ivar vlrDespCustas: Valor da despesa
                                    com custas judiciais
                                :ivar vlrDespAdvogados: Valor da despesa
                                    com advogado(s)
                                :ivar ideAdv: Identificacao do advogado
                                """

                                vlrDespCustas: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "required": True,
                                        "min_length": 4,
                                        "max_length": 15,
                                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                    },
                                )
                                vlrDespAdvogados: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "required": True,
                                        "min_length": 4,
                                        "max_length": 15,
                                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                    },
                                )
                                ideAdv: List[
                                    "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoProcJud.DespProcJud.IdeAdv"
                                ] = field(
                                    default_factory=list,
                                    metadata={
                                        "type": "Element",
                                        "max_occurs": 99,
                                    },
                                )

                                @dataclass
                                class IdeAdv:
                                    """

                                    "

                                    :ivar tpInscAdv: Tipo de inscricao
                                        do advogado
                                    :ivar nrInscAdv: Informar o numero
                                        de inscricao do advogado
                                    :ivar vlrAdv: Valor da despesa com o
                                        advogado
                                    """

                                    tpInscAdv: Optional[str] = field(
                                        default=None,
                                        metadata={
                                            "type": "Element",
                                            "required": True,
                                            "pattern": r"1|2",
                                        },
                                    )
                                    nrInscAdv: Optional[str] = field(
                                        default=None,
                                        metadata={
                                            "type": "Element",
                                            "required": True,
                                            "pattern": r"[0-9]{11}|[0-9A-Z]{14}",
                                        },
                                    )
                                    vlrAdv: Optional[str] = field(
                                        default=None,
                                        metadata={
                                            "type": "Element",
                                            "max_length": 15,
                                            "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                                        },
                                    )

                        @dataclass
                        class InfoPgtoExt:
                            """

                            "

                            :ivar indNIF: Indicativo do preenchimento do
                                NIF
                            :ivar nifBenef: NIF do beneficiario
                            :ivar relFontPg: Relacao da fonte pagadora
                                PJ e beneficiario
                            :ivar frmTribut: Forma de tributacao
                            :ivar endExt: Endereco do beneficiario
                                residente ou domiciliado no exterior
                            """

                            indNIF: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "pattern": r"1|2|3",
                                },
                            )
                            nifBenef: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "max_length": 30,
                                },
                            )
                            relFontPg: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "pattern": r"\d{3}",
                                },
                            )
                            frmTribut: Optional[str] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                    "pattern": r"[0-9]{2}",
                                },
                            )
                            endExt: Optional[
                                "Reinf.EvtRetPj.IdeEstab.IdeBenef.IdePgto.InfoPgto.InfoPgtoExt.EndExt"
                            ] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                },
                            )

                            @dataclass
                            class EndExt:
                                """

                                "

                                :ivar dscLograd: Descricao do logradouro
                                :ivar nrLograd: Numero do imovel no
                                    logradouro
                                :ivar complem: Complemento
                                :ivar bairro: Nome do bairro/distrito
                                :ivar cidade: Nome da cidade
                                :ivar estado: Nome da provincia/estado
                                :ivar codPostal: CEP
                                :ivar telef: Telefone
                                """

                                dscLograd: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 80,
                                        "white_space": "preserve",
                                    },
                                )
                                nrLograd: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 10,
                                        "white_space": "preserve",
                                    },
                                )
                                complem: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 30,
                                        "white_space": "preserve",
                                    },
                                )
                                bairro: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 60,
                                        "white_space": "preserve",
                                    },
                                )
                                cidade: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 40,
                                        "white_space": "preserve",
                                    },
                                )
                                estado: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 40,
                                        "white_space": "preserve",
                                    },
                                )
                                codPostal: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "max_length": 12,
                                        "white_space": "preserve",
                                    },
                                )
                                telef: Optional[str] = field(
                                    default=None,
                                    metadata={
                                        "type": "Element",
                                        "pattern": r"[0-9]{0,15}",
                                    },
                                )
