"""This file was generated by xsdata, v24.11, on 2026-08-22 11:29:33

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import List, Optional

from nfelib import CommonMixin

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01"


@dataclass
class TeventoResult:
    """
    Xml que contém o retorno da consulta.
    "

    :ivar dtHoraRecebimento: Data/hora de recebimento do evento pelo
        sistema. Formato AAAAMMDDHHMMSS
    :ivar nrProtocolo: Número do protocolo gerado na recepção do evento
        de fechamento
    :ivar nrRecibo: Número do recibo gerado na recepção do evento
    :ivar situacaoEvento: Situação do evento:  1-Ativo; 2-Retificado;
        3-Excluído; 4-Em Processamento; 5-Recusado
    :ivar aplicacaoRecepcao: Aplicação de recepção: 1-Webservice;
        2-Portal Web
    :ivar tpProc:
    :ivar nrProc:
    :ivar iniValid: Preencher com o mês e ano de início da validade das
        informações prestadas no evento. Formato AAAA-MM.
    :ivar fimValid: Preencher com o mês e ano de término da validade das
        informações, se houver. Formato AAAA-MM.
    :ivar tpEntLig:
    :ivar cnpjLig:
    :ivar id: ID do evento
    """

    class Meta:
        name = "TEventoResult"

    dtHoraRecebimento: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "length": 14,
        },
    )
    nrProtocolo: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
        },
    )
    nrRecibo: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "min_length": 18,
            "max_length": 52,
        },
    )
    situacaoEvento: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"1|2|3|4|5",
        },
    )
    aplicacaoRecepcao: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"1|2",
        },
    )
    tpProc: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"1|2",
        },
    )
    nrProc: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "min_length": 1,
            "max_length": 21,
        },
    )
    iniValid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"20([0-9][0-9])-(0[1-9]|1[0-2])",
        },
    )
    fimValid: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"20([0-9][0-9])-(0[1-9]|1[0-2])",
        },
    )
    tpEntLig: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"1|2|3|4",
        },
    )
    cnpjLig: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "pattern": r"[0-9A-Z]{14}",
        },
    )
    id: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass
class TregistroOcorrencias:
    """
    Define uma ocorrencia encontrada no processamento de um arquivo.
    "

    :ivar tpOcorr: Contém o tipo da ocorrencia: 1-Erro, 2-Aviso
    :ivar localErroAviso: Campo onde ocorreu o aviso/erro
    :ivar dscResp: Descrição literal da resposta
    """

    class Meta:
        name = "TRegistroOcorrencias"

    tpOcorr: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "required": True,
            "pattern": r"1|2",
        },
    )
    localErroAviso: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "required": True,
            "min_length": 1,
            "max_length": 200,
        },
    )
    dscResp: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "required": True,
            "min_length": 1,
            "max_length": 999,
        },
    )


@dataclass
class Tstatus:
    """

    "

    :ivar cdRetorno: Código do Retorno:  0-Nenhum evento encontrado;
        1-Um ou mais eventos encontrados; 3-Erro
    :ivar descRetorno: Descrição do retorno
    :ivar regOcorrs: Informaçoes de ocorrências registradas.
    """

    class Meta:
        name = "TStatus"

    cdRetorno: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "required": True,
            "pattern": r"0|1|3",
        },
    )
    descRetorno: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
            "required": True,
            "min_length": 1,
            "max_length": 1000,
        },
    )
    regOcorrs: List[TregistroOcorrencias] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01",
        },
    )


@dataclass
class Reinf(CommonMixin):
    """
    Elemento raiz do Reinf.
    "

    :ivar ideStatus: Situação atual do evento
    :ivar retornoEventos: Contém dados dos eventos que atendem ao
        critério dos parâmetros de consulta.
    """

    class Meta:
        namespace = "http://www.reinf.esocial.gov.br/schemas/retornoRecibosChaveEvento/v1_05_01"

    ideStatus: Optional[Tstatus] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    retornoEventos: Optional["Reinf.RetornoEventos"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class RetornoEventos:
        evento: List[TeventoResult] = field(
            default_factory=list,
            metadata={
                "type": "Element",
                "min_occurs": 1,
            },
        )
