"""This file was generated by xsdata, v24.11, on 2026-08-22 11:29:33

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import List, Optional

from xsdata.models.datatype import XmlDateTime

from nfelib import CommonMixin

__NAMESPACE__ = "http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_02"


@dataclass
class Reinf(CommonMixin):
    """
    Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais (EFD-
    Reinf)
    "

    :ivar evtRetCons: Evento totalizador por contribuinte
    :ivar signature:
    """

    class Meta:
        namespace = (
            "http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_02"
        )

    evtRetCons: Optional["Reinf.EvtRetCons"] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    signature: Optional[str] = field(
        default=None,
        metadata={
            "name": "Signature",
            "type": "Element",
            "namespace": "http://www.w3.org/2000/09/xmldsig#",
            "required": True,
        },
    )

    @dataclass
    class EvtRetCons:
        """

        "

        :ivar ideEvento: Informacoes de identificacao do evento
        :ivar ideContri: Informacoes de identificacao do contribuinte
        :ivar ideRecRetorno: Informacoes do recibo de retorno
        :ivar infoRecEv: Informacoes de processamento do evento
        :ivar infoCR_CNR: Informacoes relativas a totalizadores pela
            natureza do rendimento e codigo de receita
        :ivar infoTotalCR: Informacoes consolidadas dos tributos da
            empresa
        :ivar id: Identificacao unica do evento
        """

        ideEvento: Optional["Reinf.EvtRetCons.IdeEvento"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideContri: Optional["Reinf.EvtRetCons.IdeContri"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideRecRetorno: Optional["Reinf.EvtRetCons.IdeRecRetorno"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        infoRecEv: Optional["Reinf.EvtRetCons.InfoRecEv"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        infoCR_CNR: Optional["Reinf.EvtRetCons.InfoCrCnr"] = field(
            default=None,
            metadata={
                "type": "Element",
            },
        )
        infoTotalCR: Optional["Reinf.EvtRetCons.InfoTotalCr"] = field(
            default=None,
            metadata={
                "type": "Element",
            },
        )
        id: Optional[str] = field(
            default=None,
            metadata={
                "type": "Attribute",
                "required": True,
                "length": 36,
                "pattern": r"I{1}D{1}[0-9]{1}[0-9A-Z]{12}[0-9]{21}",
            },
        )

        @dataclass
        class IdeEvento:
            """

            "

            :ivar perApur: Periodo de apuracao
            """

            perApur: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"20([1-9][0-9])-(0[1-9]|1[0-2])",
                },
            )

        @dataclass
        class IdeContri:
            """

            "

            :ivar tpInsc: Tipo de Inscricao
            :ivar nrInsc: Numero de Inscricao
            """

            tpInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            nrInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[0-9A-Z]{8}|[0-9]{11}|[0-9A-Z]{14}",
                },
            )

        @dataclass
        class IdeRecRetorno:
            """

            "

            :ivar ideStatus: Situacao atual do evento
            """

            ideStatus: Optional["Reinf.EvtRetCons.IdeRecRetorno.IdeStatus"] = (
                field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                    },
                )
            )

            @dataclass
            class IdeStatus:
                """

                "

                :ivar cdRetorno: Codigo do Retorno
                :ivar descRetorno: Descricao do retorno
                :ivar regOcorrs: Informacoes de ocorrencias registradas
                """

                cdRetorno: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"0|1",
                    },
                )
                descRetorno: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 1,
                        "max_length": 1000,
                        "white_space": "preserve",
                    },
                )
                regOcorrs: List[
                    "Reinf.EvtRetCons.IdeRecRetorno.IdeStatus.RegOcorrs"
                ] = field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                    },
                )

                @dataclass
                class RegOcorrs:
                    """

                    "

                    :ivar tpOcorr: Tipo da ocorrencia
                    :ivar localErroAviso: Campo que originou o erro ou
                        aviso
                    :ivar codResp: Codigo do status da resposta do
                        processamento da consulta
                    :ivar dscResp: Descricao literal da resposta do
                        processamento da consulta
                    """

                    tpOcorr: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "pattern": r"1|2|3",
                        },
                    )
                    localErroAviso: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "max_length": 200,
                            "white_space": "preserve",
                        },
                    )
                    codResp: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "min_length": 1,
                            "max_length": 6,
                        },
                    )
                    dscResp: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "min_length": 1,
                            "max_length": 999,
                            "white_space": "preserve",
                        },
                    )

        @dataclass
        class InfoRecEv:
            """

            "

            :ivar nrRecArqBase: Recibo do arquivo de origem
            :ivar nrProtLote: Numero do protocolo de entrega do lote
            :ivar dhRecepcao: Data e hora da recepcao do evento
            :ivar dhProcess: Data e hora do processamento
            :ivar tpEv: Tipo do evento
            :ivar idEv: ID do Evento
            :ivar hash: Hash do arquivo processado
            :ivar fechRet: Indicativo da finalidade do evento de origem.
            """

            nrRecArqBase: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 0,
                    "max_length": 52,
                },
            )
            nrProtLote: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "max_length": 30,
                },
            )
            dhRecepcao: Optional[XmlDateTime] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )
            dhProcess: Optional[XmlDateTime] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )
            tpEv: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[Rr]{1}-{1}[\d]{4}",
                },
            )
            idEv: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 3,
                    "max_length": 36,
                },
            )
            hash: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 3,
                    "max_length": 60,
                },
            )
            fechRet: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"\d",
                },
            )

        @dataclass
        class InfoCrCnr:
            """

            "

            :ivar indExistInfo: Existe informacoes
            :ivar identEscritDCTF: Identificacao da escrituracao fiscal
                (EFD-Reinf) na DCTFWeb
            :ivar totApurMen: Totalizador de tributos com periodo de
                apuracao mensal
            :ivar totApurQui: Totalizador de tributos com periodo de
                apuracao quinzenal
            :ivar totApurDec: Totalizador dos tributos com periodo de
                apuracao decendial
            :ivar totApurSem: Totalizador dos tributos com periodo de
                apuracao semanal
            :ivar totApurDia: Totalizador dos tributos com periodo de
                apuracao diario
            """

            indExistInfo: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2|3",
                },
            )
            identEscritDCTF: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 1,
                    "max_length": 19,
                },
            )
            totApurMen: List["Reinf.EvtRetCons.InfoCrCnr.TotApurMen"] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                    "max_occurs": 50,
                },
            )
            totApurQui: List["Reinf.EvtRetCons.InfoCrCnr.TotApurQui"] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                    "max_occurs": 50,
                },
            )
            totApurDec: List["Reinf.EvtRetCons.InfoCrCnr.TotApurDec"] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                    "max_occurs": 60,
                },
            )
            totApurSem: List["Reinf.EvtRetCons.InfoCrCnr.TotApurSem"] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                    "max_occurs": 50,
                },
            )
            totApurDia: List["Reinf.EvtRetCons.InfoCrCnr.TotApurDia"] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                    "max_occurs": 350,
                },
            )

            @dataclass
            class TotApurMen:
                """

                "

                :ivar CRMen: Codigo de Receita - CR
                :ivar vlrCRMenInf: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRMenCalc: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRMenDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRMenSuspInf: Valor da base do tributo de
                    apuracao mensal suspenso
                :ivar vlrCRMenSuspCalc: Valor do tributo de apuracao
                    mensal suspenso
                :ivar vlrCRMenSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                :ivar natRend: Natureza do Rendimento
                """

                CRMen: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRMenInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRMenCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRMenDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRMenSuspInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRMenSuspCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRMenSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                natRend: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{5}",
                    },
                )

            @dataclass
            class TotApurQui:
                """

                "

                :ivar perApurQui: Periodo de apuracao quinzenal
                :ivar CRQui: Codigo de Receita - CR de tributo com
                    apuracao quinzenal
                :ivar vlrCRQuiInf: Valor do tributo retido com apuracao
                    quinzenal
                :ivar vlrCRQuiCalc: Valor do tributo retido com apuracao
                    quinzenal
                :ivar vlrCRQuiDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRQuiSuspInf: Valor da base do tributo de
                    apuracao quinzenal suspenso
                :ivar vlrCRQuisSuspCalc: Valor da base do tributo de
                    apuracao quinzenal suspenso
                :ivar vlrCRQuiSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                :ivar natRend: Natureza do Rendimento
                """

                perApurQui: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|2",
                    },
                )
                CRQui: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRQuiInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRQuiCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRQuiDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRQuiSuspInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRQuisSuspCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRQuiSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                natRend: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{5}",
                    },
                )

            @dataclass
            class TotApurDec:
                """

                "

                :ivar perApurDec: Periodo de apuracao decenal
                :ivar CRDec: Codigo de Receita - CR de tributo com
                    apuracao decendial
                :ivar vlrCRDecInf: Valor do tributo retido com apuracao
                    decendial
                :ivar vlrCRDecCalc: Valor do tributo retido com apuracao
                    decendial
                :ivar vlrCRDecDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRDecSuspInf: Valor do tributo de apuracao
                    decendial suspenso informado
                :ivar vlrCRDecSuspCalc: Valor do tributo de apuracao
                    decendial suspenso calculado
                :ivar vlrCRDecSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                :ivar natRend: Natureza do Rendimento
                """

                perApurDec: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|2|3",
                    },
                )
                CRDec: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRDecInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDecCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDecDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDecSuspInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDecSuspCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDecSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                natRend: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{5}",
                    },
                )

            @dataclass
            class TotApurSem:
                """

                "

                :ivar perApurSem: Periodo de apuracao semanal
                :ivar CRSem: Codigo de Receita - CR de tributo com
                    apuracao semanal
                :ivar vlrCRSemInf: Valor do tributo retido com apuracao
                    semanal
                :ivar vlrCRSemCalc: Valor do tributo retido com apuracao
                    semanal
                :ivar vlrCRSemDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRSemSuspInf: Valor da base do tributo de
                    apuracao semanal suspenso
                :ivar vlrCRSemSuspCalc: Valor da base do tributo de
                    apuracao semanal suspenso
                :ivar vlrCRSemSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                :ivar natRend: Natureza do Rendimento
                """

                perApurSem: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|2|3|4|5",
                    },
                )
                CRSem: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRSemInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRSemCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRSemDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRSemSuspInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRSemSuspCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRSemSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                natRend: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{5}",
                    },
                )

            @dataclass
            class TotApurDia:
                """

                "

                :ivar perApurDia: Periodo de apuracao diario
                :ivar CRDia: Codigo de Receita - CR de tributo com
                    apuracao diario
                :ivar vlrCRDiaInf: Valor do tributo retido com apuracao
                    diaria
                :ivar vlrCRDiaCalc: Valor do tributo retido com apuracao
                    diaria
                :ivar vlrCRDiaDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRDiaSuspInf: Valor da base do tributo de
                    apuracao diario suspenso
                :ivar vlrCRDiaSuspCalc: Valor da base do tributo de
                    apuracao diario suspenso
                :ivar vlrCRDiaSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                :ivar natRend: Natureza do Rendimento
                """

                perApurDia: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{1,2}",
                    },
                )
                CRDia: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRDiaInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDiaCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDiaDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDiaSuspInf: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDiaSuspCalc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDiaSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                natRend: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{5}",
                    },
                )

        @dataclass
        class InfoTotalCr:
            """

            "

            :ivar totApurMen: Totalizador de tributos com periodo de
                apuracao mensal
            :ivar totApurQui: Totalizador de tributos com periodo de
                apuracao quinzenal
            :ivar totApurDec: Totalizador dos tributos com periodo de
                apuracao decendial
            :ivar totApurSem: Totalizador dos tributos com periodo de
                apuracao semanal
            :ivar totApurDia: Totalizador dos tributos com periodo de
                apuracao diario
            """

            totApurMen: List["Reinf.EvtRetCons.InfoTotalCr.TotApurMen"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 50,
                    },
                )
            )
            totApurQui: List["Reinf.EvtRetCons.InfoTotalCr.TotApurQui"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 50,
                    },
                )
            )
            totApurDec: List["Reinf.EvtRetCons.InfoTotalCr.TotApurDec"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 60,
                    },
                )
            )
            totApurSem: List["Reinf.EvtRetCons.InfoTotalCr.TotApurSem"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 50,
                    },
                )
            )
            totApurDia: List["Reinf.EvtRetCons.InfoTotalCr.TotApurDia"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 350,
                    },
                )
            )

            @dataclass
            class TotApurMen:
                """

                "

                :ivar CRMen: Codigo de Receita - CR
                :ivar vlrCRMenDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRMenSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                """

                CRMen: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRMenDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRMenSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class TotApurQui:
                """

                "

                :ivar perApurQui: Periodo de apuracao quinzenal
                :ivar CRQui: Codigo de Receita - CR de tributo com
                    apuracao quinzenal
                :ivar vlrCRQuiDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRQuiSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                """

                perApurQui: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|2",
                    },
                )
                CRQui: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRQuiDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRQuiSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class TotApurDec:
                """

                "

                :ivar perApurDec: Periodo de apuracao decenal
                :ivar CRDec: Codigo de Receita - CR de tributo com
                    apuracao decendial
                :ivar vlrCRDecDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRDecSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                """

                perApurDec: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|2|3",
                    },
                )
                CRDec: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRDecDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDecSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class TotApurSem:
                """

                "

                :ivar perApurSem: Periodo de apuracao semanal
                :ivar CRSem: Codigo de Receita - CR de tributo com
                    apuracao semanal
                :ivar vlrCRSemDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRSemSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                """

                perApurSem: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|2|3|4|5",
                    },
                )
                CRSem: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRSemDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRSemSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class TotApurDia:
                """

                "

                :ivar perApurDia: Periodo de apuracao diario
                :ivar CRDia: Codigo de Receita - CR de tributo com
                    apuracao diario
                :ivar vlrCRDiaDCTF: Valor do tributo retido com apuracao
                    mensal
                :ivar vlrCRDiaSuspDCTF: Valor do tributo retido com
                    apuracao mensal
                """

                perApurDia: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"\d{1,2}",
                    },
                )
                CRDia: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                    },
                )
                vlrCRDiaDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRDiaSuspDCTF: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
