"""This file was generated by xsdata, v24.11, on 2026-08-22 11:29:33

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import List, Optional

from xsdata.models.datatype import XmlDateTime

from nfelib import CommonMixin

__NAMESPACE__ = (
    "http://www.reinf.esocial.gov.br/schemas/evtTotalContrib/v2_01_02"
)


@dataclass
class Reinf(CommonMixin):
    """
    Escrituracao Fiscal Digital de Retencoes e Outras Informacoes Fiscais (EFD-
    Reinf)
    "

    :ivar evtTotalContrib: Evento totalizador por contribuinte
    :ivar signature:
    """

    class Meta:
        namespace = (
            "http://www.reinf.esocial.gov.br/schemas/evtTotalContrib/v2_01_02"
        )

    evtTotalContrib: Optional["Reinf.EvtTotalContrib"] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    signature: Optional[str] = field(
        default=None,
        metadata={
            "name": "Signature",
            "type": "Element",
            "namespace": "http://www.w3.org/2000/09/xmldsig#",
            "required": True,
        },
    )

    @dataclass
    class EvtTotalContrib:
        """

        "

        :ivar ideEvento: Informacoes de identificacao do evento
        :ivar ideContri: Informacoes de identificacao do contribuinte
        :ivar ideRecRetorno: Informacoes do recibo de retorno
        :ivar infoRecEv: Informacoes de processamento dos eventos
        :ivar infoTotalContrib: Informacoes relativas a totalizadores
            por contribuinte
        :ivar id: Identificacao unica do evento
        """

        ideEvento: Optional["Reinf.EvtTotalContrib.IdeEvento"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideContri: Optional["Reinf.EvtTotalContrib.IdeContri"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        ideRecRetorno: Optional["Reinf.EvtTotalContrib.IdeRecRetorno"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        infoRecEv: Optional["Reinf.EvtTotalContrib.InfoRecEv"] = field(
            default=None,
            metadata={
                "type": "Element",
                "required": True,
            },
        )
        infoTotalContrib: Optional[
            "Reinf.EvtTotalContrib.InfoTotalContrib"
        ] = field(
            default=None,
            metadata={
                "type": "Element",
            },
        )
        id: Optional[str] = field(
            default=None,
            metadata={
                "type": "Attribute",
                "required": True,
                "length": 36,
                "pattern": r"I{1}D{1}[0-9]{1}[0-9A-Z]{12}[0-9]{21}",
            },
        )

        @dataclass
        class IdeEvento:
            """

            "

            :ivar perApur: Periodo de apuracao
            """

            perApur: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"20([1-9][0-9])-(0[1-9]|1[0-2])",
                },
            )

        @dataclass
        class IdeContri:
            """

            "

            :ivar tpInsc: Tipo de Inscricao
            :ivar nrInsc: Numero de Inscricao
            """

            tpInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2",
                },
            )
            nrInsc: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[0-9A-Z]{8}|[0-9]{11}|[0-9A-Z]{14}",
                },
            )

        @dataclass
        class IdeRecRetorno:
            """

            "

            :ivar ideStatus: Situacao atual do evento
            """

            ideStatus: Optional[
                "Reinf.EvtTotalContrib.IdeRecRetorno.IdeStatus"
            ] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )

            @dataclass
            class IdeStatus:
                """

                "

                :ivar cdRetorno: Codigo do Retorno
                :ivar descRetorno: Descricao do retorno
                :ivar regOcorrs: Informacoes de ocorrencias registradas
                """

                cdRetorno: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"0|1",
                    },
                )
                descRetorno: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 1,
                        "max_length": 1000,
                        "white_space": "preserve",
                    },
                )
                regOcorrs: List[
                    "Reinf.EvtTotalContrib.IdeRecRetorno.IdeStatus.RegOcorrs"
                ] = field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                    },
                )

                @dataclass
                class RegOcorrs:
                    """

                    "

                    :ivar tpOcorr: Tipo da ocorrencia
                    :ivar localErroAviso: Campo que originou o erro ou
                        aviso
                    :ivar codResp: Codigo do status da resposta do
                        processamento da consulta
                    :ivar dscResp: Descricao literal da resposta do
                        processamento da consulta
                    """

                    tpOcorr: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "pattern": r"1|2|3",
                        },
                    )
                    localErroAviso: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "max_length": 200,
                            "white_space": "preserve",
                        },
                    )
                    codResp: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "min_length": 1,
                            "max_length": 6,
                        },
                    )
                    dscResp: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "min_length": 1,
                            "max_length": 999,
                            "white_space": "preserve",
                        },
                    )

        @dataclass
        class InfoRecEv:
            """

            "

            :ivar nrProtEntr: Numero do protocolo de entrega do evento
            :ivar nrRecArqBase: Recibo do arquivo de origem
            :ivar dhRecepcao: Data e hora da recepcao do evento
            :ivar dhProcess: Data e hora do processamento
            :ivar tpEv: Tipo do evento
            :ivar idEv: ID do Evento
            :ivar hash: Hash do arquivo processado
            """

            nrProtEntr: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 1,
                    "max_length": 49,
                },
            )
            nrRecArqBase: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "max_length": 52,
                },
            )
            dhRecepcao: Optional[XmlDateTime] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )
            dhProcess: Optional[XmlDateTime] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )
            tpEv: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"[Rr]{1}-{1}[\d]{4}",
                },
            )
            idEv: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 1,
                    "max_length": 36,
                },
            )
            hash: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 3,
                    "max_length": 60,
                },
            )

        @dataclass
        class InfoTotalContrib:
            """

            "

            :ivar indExistInfo: Existe informacoes
            :ivar identEscritDCTF: Identificacao da escrituracao fiscal
                (EFD-Reinf) na DCTFWeb
            :ivar RTom: Totalizador das bases de calculo e retencoes
                sobre servicos tomados
            :ivar RPrest: Totalizador das bases de calculo e das
                retencoes sobre servicos prestados
            :ivar RRecRepAD: Totalizador das bases de calculo e
                retencoes sobre recursos repassados a Associacoes
                Desportivas
            :ivar RComl: Totalizador das contribuicoes sobre
                comercializacao
            :ivar RAquis: Totalizador das contribuicoes sobre aquisicao
                de producao rural
            :ivar RCPRB: Totalizador da CPRB
            """

            indExistInfo: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "pattern": r"1|2|3",
                },
            )
            identEscritDCTF: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                    "min_length": 8,
                    "max_length": 19,
                },
            )
            RTom: List["Reinf.EvtTotalContrib.InfoTotalContrib.Rtom"] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                },
            )
            RPrest: List["Reinf.EvtTotalContrib.InfoTotalContrib.Rprest"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                    },
                )
            )
            RRecRepAD: List[
                "Reinf.EvtTotalContrib.InfoTotalContrib.RrecRepAd"
            ] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                },
            )
            RComl: List["Reinf.EvtTotalContrib.InfoTotalContrib.Rcoml"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 3,
                    },
                )
            )
            RAquis: List["Reinf.EvtTotalContrib.InfoTotalContrib.Raquis"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 10,
                    },
                )
            )
            RCPRB: List["Reinf.EvtTotalContrib.InfoTotalContrib.Rcprb"] = (
                field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 4,
                    },
                )
            )

            @dataclass
            class Rtom:
                """

                "

                :ivar cnpjPrestador: CNPJ do Prestador de Servicos
                :ivar cno: Nro. CNO
                :ivar vlrTotalBaseRet: Base de calculo da retencao da
                    contribuicao previdenciaria.
                :ivar infoCRTom: Informacoes de retencoes sobre servicos
                    prestados
                """

                cnpjPrestador: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"[0-9A-Z]{14}",
                    },
                )
                cno: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "pattern": r"\d{10,14}",
                    },
                )
                vlrTotalBaseRet: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                infoCRTom: List[
                    "Reinf.EvtTotalContrib.InfoTotalContrib.Rtom.InfoCrtom"
                ] = field(
                    default_factory=list,
                    metadata={
                        "type": "Element",
                        "max_occurs": 2,
                    },
                )

                @dataclass
                class InfoCrtom:
                    """

                    "

                    :ivar CRTom: Cod. de Receita - Servicos Tomados
                    :ivar vlrCRTom: Valor da CP correspondente ao CR
                        informado em {CRTom}
                    :ivar vlrCRTomSusp: Valor suspenso da CP
                    """

                    CRTom: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "required": True,
                            "min_length": 4,
                            "max_length": 6,
                            "pattern": r"114106|116201",
                        },
                    )
                    vlrCRTom: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "max_length": 15,
                            "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                        },
                    )
                    vlrCRTomSusp: Optional[str] = field(
                        default=None,
                        metadata={
                            "type": "Element",
                            "max_length": 15,
                            "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                        },
                    )

            @dataclass
            class Rprest:
                """

                "

                :ivar tpInscTomador: Tipo de Inscricao do
                    Contratante(tomador)
                :ivar nrInscTomador: Numero de Inscricao
                :ivar vlrTotalBaseRet: Base de calculo da retencao da
                    contribuicao previdenciaria.
                :ivar vlrTotalRetPrinc: Valor da retencao principal das
                    notas fiscais de servico
                :ivar vlrTotalRetAdic: Soma do valor do adicional de
                    retencao das notas fiscais
                :ivar vlrTotalNRetPrinc: Valor da retencao principal que
                    deixou de ser efetuada
                :ivar vlrTotalNRetAdic: Valor da retencao adicional que
                    deixou de ser efetuada
                """

                tpInscTomador: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"1|4",
                    },
                )
                nrInscTomador: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "pattern": r"[0-9]{12}|[0-9A-Z]{14}",
                    },
                )
                vlrTotalBaseRet: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrTotalRetPrinc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrTotalRetAdic: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrTotalNRetPrinc: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrTotalNRetAdic: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class RrecRepAd:
                """

                "

                :ivar CRRecRepAD: Cod de Receita CP sobre repasses a
                    associacoes desportivas
                :ivar vlrCRRecRepAD: CP sobre Repasses a Associacoes
                    Desportivas
                :ivar vlrCRRecRepADSusp: Retencao de CP nao efetuada ou
                    depositada em juizo por decisao
                    judicial/administrativa
                """

                CRRecRepAD: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                        "pattern": r"115102",
                    },
                )
                vlrCRRecRepAD: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRRecRepADSusp: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class Rcoml:
                """

                "

                :ivar CRComl: Cod Receita - CRs/comercializacao
                :ivar vlrCRComl: Valor da CP correspondente ao CR
                    informado em {CRComl}
                :ivar vlrCRComlSusp: Valor suspenso da CP correspondente
                    ao CR informado em {CRComl}
                """

                CRComl: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                        "pattern": r"165701|165702|164605|164606|121302|121304",
                    },
                )
                vlrCRComl: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRComlSusp: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class Raquis:
                """

                "

                :ivar CRAquis: Cod Receita - Aquisicao
                :ivar vlrCRAquis: Valor da CP correspondente ao CR
                    informado em {CRAquis}
                :ivar vlrCRAquisSusp: Valor suspenso da CP
                    correspondente ao CR informado em {CRAquis}
                """

                CRAquis: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                        "pattern": r"165601|165602|165603|165604|164603|164604|164607|164608|121306|121307",
                    },
                )
                vlrCRAquis: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRAquisSusp: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )

            @dataclass
            class Rcprb:
                """

                "

                :ivar CRCPRB: CR relativo a CPRB
                :ivar vlrCRCPRB: Valor da CPRB
                :ivar vlrCRCPRBSusp: Valor da CPRB com exigibilidade
                    suspensa
                """

                CRCPRB: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 6,
                        "pattern": r"299101|298501|298504|298506",
                    },
                )
                vlrCRCPRB: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "required": True,
                        "min_length": 4,
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
                vlrCRCPRBSusp: Optional[str] = field(
                    default=None,
                    metadata={
                        "type": "Element",
                        "max_length": 15,
                        "pattern": r"[0-9]{1,12}[,][0-9]{2}",
                    },
                )
