"""This file was generated by xsdata, v24.11, on 2026-08-22 11:33:22

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from nfelib.gnre.bindings.v2_0.tipos_basico_gnre_v1_00 import (
    TsimNao,
    Tuf,
)

__NAMESPACE__ = "http://www.gnre.pe.gov.br"


class TconsultaConfigUfAmbiente(Enum):
    VALUE_1 = "1"
    VALUE_2 = "2"


@dataclass
class TconsultaConfigUf:
    class Meta:
        name = "TConsultaConfigUf"
        namespace = "http://www.gnre.pe.gov.br"

    ambiente: Optional[TconsultaConfigUfAmbiente] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    uf: Optional[Tuf] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
    receita: Optional["TconsultaConfigUf.Receita"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    tiposGnre: Optional[TsimNao] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class Receita:
        value: str = field(
            default="",
            metadata={
                "required": True,
                "pattern": r"[0-9]{6}",
            },
        )
        courier: Optional[TsimNao] = field(
            default=None,
            metadata={
                "type": "Attribute",
            },
        )
