"""This file was generated by xsdata, v24.3.1, on 2024-04-05 08:28:03

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass

from nfelib.nfcom.bindings.v1_0.cons_stat_serv_nfcom_tipos_basico_v1_00 import (
    TconsStatServ,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


@dataclass
class ConsStatServNfcom(TconsStatServ):
    """
    Schema XML de validação do Pedido de Consulta do Status do Serviço NFCom.
    """

    class Meta:
        name = "consStatServNFCom"
        namespace = "http://www.portalfiscal.inf.br/nfcom"
