"""This file was generated by xsdata, v24.3.1, on 2024-04-05 08:28:03

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional

from nfelib import CommonMixin
from nfelib.nfcom.bindings.v1_0.tipos_geral_nfcom_v1_00 import (
    Tamb,
    TcodUfIbge,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


class ProcEventoNfcomVersao(Enum):
    VALUE_1_00 = "1.00"


class ProtNfcomVersao(Enum):
    VALUE_1_00 = "1.00"


@dataclass
class TconsSitNfcom(CommonMixin):
    """
    Tipo Pedido de Consulta da Situação Atual da NFCom.

    :ivar tpAmb: Identificação do Ambiente: 1 - Produção; 2 -
        Homologação;
    :ivar xServ: Serviço Solicitado
    :ivar chNFCom: Chaves de acesso do NFCom
    :ivar versao:
    """

    class Meta:
        name = "TConsSitNFCom"

    tpAmb: Optional[Tamb] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
        },
    )
    xServ: str = field(
        init=False,
        default="CONSULTAR",
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    chNFCom: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
            "max_length": 44,
            "white_space": "preserve",
            "pattern": r"[0-9]{44}",
        },
    )
    versao: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "pattern": r"1\.00",
        },
    )


@dataclass
class TretConsSitNfcom(CommonMixin):
    """
    Tipo Retorno de Pedido de Consulta da Situação Atual de NFCom.

    :ivar tpAmb: Identificação do Ambiente: 1 - Produção 2 - Homologação
    :ivar verAplic: Versão do Aplicativo que processou o NFCom
    :ivar cStat: Código do status da mensagem enviada.
    :ivar xMotivo: Descrição literal do status do serviço solicitado.
    :ivar cUF: código da UF de atendimento
    :ivar protNFCom:
    :ivar procEventoNFCom:
    :ivar versao:
    """

    class Meta:
        name = "TRetConsSitNFCom"

    tpAmb: Optional[Tamb] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
        },
    )
    verAplic: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
            "min_length": 1,
            "max_length": 20,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    cStat: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[0-9]{3}",
        },
    )
    xMotivo: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
            "min_length": 1,
            "max_length": 255,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    cUF: Optional[TcodUfIbge] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
            "required": True,
        },
    )
    protNFCom: Optional["TretConsSitNfcom.ProtNfcom"] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
        },
    )
    procEventoNFCom: List["TretConsSitNfcom.ProcEventoNfcom"] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
        },
    )
    versao: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "pattern": r"1\.00",
        },
    )

    @dataclass
    class ProtNfcom(CommonMixin):
        """
        :ivar any_element: Retornar protNFCom da versão correspondente
            da NFCom autorizada
        :ivar versao:
        """

        any_element: Optional[object] = field(
            default=None,
            metadata={
                "type": "Wildcard",
                "namespace": "##any",
                "process_contents": "skip",
            },
        )
        versao: Optional[ProtNfcomVersao] = field(
            default=None,
            metadata={
                "type": "Attribute",
                "required": True,
                "white_space": "preserve",
            },
        )

    @dataclass
    class ProcEventoNfcom(CommonMixin):
        """
        :ivar any_element: Retornar procEventoNFCom da versão
            correspondente do evento NFCom autorizado
        :ivar versao:
        """

        any_element: Optional[object] = field(
            default=None,
            metadata={
                "type": "Wildcard",
                "namespace": "##any",
                "process_contents": "skip",
            },
        )
        versao: Optional[ProcEventoNfcomVersao] = field(
            default=None,
            metadata={
                "type": "Attribute",
                "required": True,
                "white_space": "preserve",
            },
        )
