exclude: |
  (?x)
  .*/bindings/.*\.py$|
  .*/schemas/.*\.xsd$|
  .*/samples/.*\.xml$|
  .*/wsdl/.*\.wsdl$|
  .*/soap/.*\.py$|
  nfelib/nfe/ws/edoc_legacy.py|
  nfelib/nfe/client/v4_0/servers.py|
  nfelib/ctee/client/v4_0/servers.py|
  ^README\.md$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes]
      - id: ruff-format
        exclude: ^nfelib/[^/]+\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^(nfelib/)
        additional_dependencies:
          - types-requests
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
        types_or: [markdown]
        args: [--prose-wrap=always, --print-width=88]
        exclude: ^nfelib/[^/]+\.xml$
