"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:20

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfse.bindings.v1_0.tipos_complexos_v1_00 import Tcnfse

__NAMESPACE__ = "http://www.sped.fazenda.gov.br/nfse"


@dataclass(kw_only=True)
class Nfse(Tcnfse):
    """
    Schema XML da Nota Fiscal de Serviços Eletrônica - NFS-e.
    """

    class Meta:
        name = "NFSe"
        namespace = "http://www.sped.fazenda.gov.br/nfse"
