"""This file was generated by xsdata, v25.7, on 2026-07-13 02:25:57

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfse.bindings.v1_0.tipos_eventos_v1_00 import TcpedRegEvt

__NAMESPACE__ = "http://www.sped.fazenda.gov.br/nfse"


@dataclass
class PedRegEvento(TcpedRegEvt):
    """
    Schema XML do Pedido de Registro de Eventos.
    """

    class Meta:
        name = "pedRegEvento"
        namespace = "http://www.sped.fazenda.gov.br/nfse"
