"""This file was generated by xsdata, v25.7, on 2026-09-28 16:07:02

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nf3e.bindings.v1_0.cons_reci_nf3e_tipos_basico_v1_00 import (
    TconsReciNf3E,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nf3e"


@dataclass
class ConsReciNf3E(TconsReciNf3E):
    """
    Schema XML de validação do Pedido de Consulta de NF-3e.
    """

    class Meta:
        name = "consReciNF3e"
        namespace = "http://www.portalfiscal.inf.br/nf3e"
