"""This file was generated by xsdata, v24.2.1, on 2024-02-24 11:16:39

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass
from nfelib.mdfe.bindings.v3_0.leiaute_dist_mdfe_v3_00 import TdistDfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


@dataclass
class DistMdfe(TdistDfe):
    """
    Solicitação de distribuição de MDF-e para o Ambiente Autorizador.
    """

    class Meta:
        name = "distMDFe"
        namespace = "http://www.portalfiscal.inf.br/mdfe"
