"""This file was generated by xsdata, v26.2, on 2026-09-25 12:59:56

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


class EvIncCondutorMdfeDescEvento(Enum):
    INCLUSAO_CONDUTOR = "Inclusao Condutor"


@dataclass
class EvIncCondutorMdfe:
    """
    Schema XML de validação do evento de inclusao de condutor 110114.

    :ivar descEvento: Descrição do Evento - “Inclusao Condutor”
    :ivar condutor: Informações do(s) Condutor(s) do veículo
    """

    class Meta:
        name = "evIncCondutorMDFe"
        namespace = "http://www.portalfiscal.inf.br/mdfe"

    descEvento: EvIncCondutorMdfeDescEvento = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
        }
    )
    condutor: EvIncCondutorMdfe.Condutor = field(
        metadata={
            "type": "Element",
        }
    )

    @dataclass
    class Condutor:
        """
        :ivar xNome: Nome do Condutor
        :ivar CPF: CPF do Condutor
        """

        xNome: str = field(
            metadata={
                "type": "Element",
                "min_length": 2,
                "max_length": 60,
                "white_space": "preserve",
                "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
            }
        )
        CPF: str = field(
            metadata={
                "type": "Element",
                "white_space": "preserve",
                "pattern": r"[0-9]{11}",
            }
        )
