"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:19

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

from nfelib.mdfe.bindings.v3_0.tipos_geral_mdfe_v3_00 import Tamb

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


@dataclass(kw_only=True)
class TmdfeDfe:
    """
    Tipo Documento Fiscal Eletrônico MDF-e.
    """

    class Meta:
        name = "TMDFeDFe"

    procMDFe: None | TmdfeDfe.ProcMdfe = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
        },
    )
    procEventoMDFe: list[TmdfeDfe.ProcEventoMdfe] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
        },
    )

    @dataclass(kw_only=True)
    class ProcMdfe:
        """
        :ivar any_element: Autorização de Uso do MDF-e
        :ivar versao:
        """

        any_element: list[object] = field(
            default_factory=list,
            metadata={
                "type": "Wildcard",
                "namespace": "##any",
                "max_occurs": 2,
            },
        )
        versao: None | str = field(
            default=None,
            metadata={
                "type": "Attribute",
                "pattern": r"3\.00",
            },
        )

    @dataclass(kw_only=True)
    class ProcEventoMdfe:
        """
        :ivar any_element: Demais eventos vinculados ao MDF-e
        :ivar versao:
        """

        any_element: list[object] = field(
            default_factory=list,
            metadata={
                "type": "Wildcard",
                "namespace": "##any",
                "max_occurs": 2,
            },
        )
        versao: None | str = field(
            default=None,
            metadata={
                "type": "Attribute",
                "pattern": r"3\.00",
            },
        )


@dataclass(kw_only=True)
class TmdfeConsultaDfe:
    """
    Tipo Pedido de Consulta do Manifesto Eletrônico de Documentos Fiscais.

    :ivar tpAmb: Identificação do Ambiente: 1 - Produção 2 - Homologação
    :ivar xServ: Serviço Solicitado
    :ivar chMDFe: Chaves de acesso do MDF-e, compostas por: UF do
        emitente, AAMM da emissão do MDF-e, CNPJ do emitente, modelo,
        série e número do MDF-e e código numérico + DV.
    :ivar versao:
    """

    class Meta:
        name = "TMDFeConsultaDFe"

    tpAmb: None | Tamb = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
        },
    )
    xServ: None | str = field(
        init=False,
        default="CONSULTAR",
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    chMDFe: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
            "max_length": 44,
            "white_space": "preserve",
            "pattern": r"[0-9]{6}[A-Z0-9]{12}[0-9]{26}",
        },
    )
    versao: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "pattern": r"3\.00",
        },
    )


@dataclass(kw_only=True)
class TretMdfeConsultaDfe:
    """
    Tipo Retorno de Pedido de Consulta do Manifesto Eletrônico de
    Documentos Fiscais.

    :ivar tpAmb: Identificação do Ambiente: 1 - Produção 2 - Homologação
    :ivar verAplic: Versão do Aplicativo que processou a consulta do
        MDF-e
    :ivar cStat: Código do status da consulta do MDF-e
    :ivar xMotivo: Descrição literal do status da consulta do MDF-e
    :ivar MDFeDFe:
    :ivar versao:
    """

    class Meta:
        name = "TRetMDFeConsultaDFe"

    tpAmb: None | Tamb = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
        },
    )
    verAplic: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
            "min_length": 1,
            "max_length": 20,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    cStat: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
            "white_space": "preserve",
            "pattern": r"[0-9]{3,4}",
        },
    )
    xMotivo: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
            "min_length": 1,
            "max_length": 255,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    MDFeDFe: None | TmdfeDfe = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/mdfe",
        },
    )
    versao: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "pattern": r"3\.00",
        },
    )
