"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:19

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.mdfe.bindings.v3_0.evento_mdfe_tipos_basico_v3_00 import (
    TprocEvento,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


@dataclass(kw_only=True)
class ProcEventoMdfe(TprocEvento):
    """
    Pedido de Registro de Evento de MDF-e processado.
    """

    class Meta:
        name = "procEventoMDFe"
        namespace = "http://www.portalfiscal.inf.br/mdfe"
