"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:19

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.mdfe.bindings.v3_0.leiaute_dist_mdfe_v3_00 import TretDistDfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


@dataclass(kw_only=True)
class RetDistMdfe(TretDistDfe):
    """
    Retorno de pedido de distribuição de MDF-e.
    """

    class Meta:
        name = "retDistMDFe"
        namespace = "http://www.portalfiscal.inf.br/mdfe"
