"""This file was generated by xsdata, v24.11, on 2025-07-14 04:38:46

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.mdfe.bindings.v3_0.evento_mdfe_tipos_basico_v3_00 import TretEvento

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


@dataclass
class RetEventoMdfe(TretEvento):
    """
    Schema XML de validação do retorno Pedido de Cancelamento do MDF-e.
    """

    class Meta:
        name = "retEventoMDFe"
        namespace = "http://www.portalfiscal.inf.br/mdfe"
