"""This file was generated by xsdata, v24.11, on 2026-03-08 12:13:15

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.nfe_evento_cce.bindings.v1_0.leiaute_cce_v1_00 import TenvEvento

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class EnvEvento(TenvEvento):
    """
    Schema XML de validação do lote de envio do evento carta de correção.
    """

    class Meta:
        name = "envEvento"
        namespace = "http://www.portalfiscal.inf.br/nfe"
