"""This file was generated by xsdata, v24.2.1, on 2025-03-24 16:18:28

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from nfelib.mdfe.soap.v3_0.mdferecepcaosinc import (
    MdfeRecepcaoSincSoap12MdfeRecepcao,
    MdfeRecepcaoSincSoap12MdfeRecepcaoInput,
    MdfeRecepcaoSincSoap12MdfeRecepcaoOutput,
    MdfeDadosMsg,
    MdfeRecepcaoResult,
)

__all__ = [
    "MdfeRecepcaoSincSoap12MdfeRecepcao",
    "MdfeRecepcaoSincSoap12MdfeRecepcaoInput",
    "MdfeRecepcaoSincSoap12MdfeRecepcaoOutput",
    "MdfeDadosMsg",
    "MdfeRecepcaoResult",
]
