"""This file was generated by xsdata, v24.2.1, on 2025-03-24 16:18:28

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from nfelib import CommonMixin
from typing import List, Optional

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoSinc"


@dataclass
class MdfeRecepcaoSincSoap12MdfeRecepcaoInput(CommonMixin):
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    Body: Optional["MdfeRecepcaoSincSoap12MdfeRecepcaoInput.Body"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class Body(CommonMixin):
        mdfeDadosMsg: Optional[str] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoSinc",
            },
        )


@dataclass
class MdfeDadosMsg(CommonMixin):
    class Meta:
        name = "mdfeDadosMsg"
        namespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoSinc"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class MdfeRecepcaoResult(CommonMixin):
    class Meta:
        name = "mdfeRecepcaoResult"
        namespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoSinc"

    content: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class MdfeRecepcaoSincSoap12MdfeRecepcaoOutput(CommonMixin):
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    Body: Optional["MdfeRecepcaoSincSoap12MdfeRecepcaoOutput.Body"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class Body(CommonMixin):
        mdfeRecepcaoResult: Optional[MdfeRecepcaoResult] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoSinc",
            },
        )
        Fault: Optional[
            "MdfeRecepcaoSincSoap12MdfeRecepcaoOutput.Body.Fault"
        ] = field(
            default=None,
            metadata={
                "type": "Element",
            },
        )

        @dataclass
        class Fault(CommonMixin):
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )


class MdfeRecepcaoSincSoap12MdfeRecepcao:
    style = "document"
    location = (
        "https://mdfe.svrs.rs.gov.br/ws/MDFeRecepcaoSinc/MDFeRecepcaoSinc.asmx"
    )
    transport = "http://schemas.xmlsoap.org/soap/http"
    soapAction = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoSinc/mdfeRecepcao"
    input = MdfeRecepcaoSincSoap12MdfeRecepcaoInput
    output = MdfeRecepcaoSincSoap12MdfeRecepcaoOutput
