"""This file was generated by xsdata, v24.2.1, on 2025-03-24 16:18:26

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from nfelib import CommonMixin
from typing import Dict, List, Optional

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc"


@dataclass
class MdfeCabecMsg(CommonMixin):
    class Meta:
        name = "mdfeCabecMsg"
        namespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc"

    cUF: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    versaoDados: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    any_attributes: Dict[str, str] = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##any",
        },
    )


@dataclass
class MdfeConsNaoEncResult(CommonMixin):
    class Meta:
        name = "mdfeConsNaoEncResult"
        namespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc"

    content: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class MdfeDadosMsg(CommonMixin):
    class Meta:
        name = "mdfeDadosMsg"
        namespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc"

    content: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class MdfeConsNaoEncSoap12MdfeConsNaoEncInput(CommonMixin):
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    Body: Optional["MdfeConsNaoEncSoap12MdfeConsNaoEncInput.Body"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    Header: Optional["MdfeConsNaoEncSoap12MdfeConsNaoEncInput.Header"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class Body(CommonMixin):
        mdfeDadosMsg: Optional[MdfeDadosMsg] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc",
            },
        )

    @dataclass
    class Header(CommonMixin):
        mdfeCabecMsg: Optional[MdfeCabecMsg] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc",
            },
        )


@dataclass
class MdfeConsNaoEncSoap12MdfeConsNaoEncOutput(CommonMixin):
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    Body: Optional["MdfeConsNaoEncSoap12MdfeConsNaoEncOutput.Body"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    Header: Optional["MdfeConsNaoEncSoap12MdfeConsNaoEncOutput.Header"] = (
        field(
            default=None,
            metadata={
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body(CommonMixin):
        mdfeConsNaoEncResult: Optional[MdfeConsNaoEncResult] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc",
            },
        )
        Fault: Optional[
            "MdfeConsNaoEncSoap12MdfeConsNaoEncOutput.Body.Fault"
        ] = field(
            default=None,
            metadata={
                "type": "Element",
            },
        )

        @dataclass
        class Fault(CommonMixin):
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )

    @dataclass
    class Header(CommonMixin):
        mdfeCabecMsg: Optional[MdfeCabecMsg] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc",
            },
        )


class MdfeConsNaoEncSoap12MdfeConsNaoEnc:
    style = "document"
    location = (
        "https://mdfe.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx"
    )
    transport = "http://schemas.xmlsoap.org/soap/http"
    soapAction = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc/mdfeConsNaoEnc"
    input = MdfeConsNaoEncSoap12MdfeConsNaoEncInput
    output = MdfeConsNaoEncSoap12MdfeConsNaoEncOutput
