"""This file was generated by xsdata, v25.7, on 2026-07-13 02:25:56

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://www.portalfiscal.inf.br/mdfe"


class Tamb(Enum):
    """
    Tipo Ambiente.
    """

    VALUE_1 = "1"
    VALUE_2 = "2"
