# Auto-generated file. Do not edit manually.

servers = {
    'AM': {
        'prod_server': 'homnfe.sefaz.am.gov.br',
        'dev_server': 'homnfe.sefaz.am.gov.br',
        'NfeInutilizacao': '/services2/services/NfeInutilizacao4',
        'NfeConsultaProtocolo': '/services2/services/NfeConsulta4',
        'NfeStatusServico': '/services2/services/NfeStatusServico4',
        'NfeConsultaCadastro': '/services2/services/CadConsultaCadastro4',
        'RecepcaoEvento': '/services2/services/RecepcaoEvento4',
        'NFeAutorizacao': '/services2/services/NfeAutorizacao4',
        'NFeRetAutorizacao': '/services2/services/NfeRetAutorizacao4',
    },
    'BA': {
        'prod_server': 'hnfe.sefaz.ba.gov.br',
        'dev_server': 'hnfe.sefaz.ba.gov.br',
        'NfeInutilizacao': '/webservices/NFeInutilizacao4/NFeInutilizacao4.asmx',
        'NfeConsultaProtocolo': '/webservices/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
        'NfeStatusServico': '/webservices/NFeStatusServico4/NFeStatusServico4.asmx',
        'NfeConsultaCadastro': '/webservices/CadConsultaCadastro4/CadConsultaCadastro4.asmx',
        'RecepcaoEvento': '/webservices/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
        'NFeAutorizacao': '/webservices/NFeAutorizacao4/NFeAutorizacao4.asmx',
        'NFeRetAutorizacao': '/webservices/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
    },
    'GO': {
        'prod_server': 'homolog.sefaz.go.gov.br',
        'dev_server': 'homolog.sefaz.go.gov.br',
        'NfeInutilizacao': '/nfe/services/NFeInutilizacao4?wsdl',
        'NfeConsultaProtocolo': '/nfe/services/NFeConsultaProtocolo4?wsdl',
        'NfeStatusServico': '/nfe/services/NFeStatusServico4?wsdl',
        'NfeConsultaCadastro': '/nfe/services/CadConsultaCadastro4?wsdl',
        'RecepcaoEvento': '/nfe/services/NFeRecepcaoEvento4?wsdl',
        'NFeAutorizacao': '/nfe/services/NFeAutorizacao4?wsdl',
        'NFeRetAutorizacao': '/nfe/services/NFeRetAutorizacao4?wsdl',
    },
    'MG': {
        'prod_server': 'hnfe.fazenda.mg.gov.br',
        'dev_server': 'hnfe.fazenda.mg.gov.br',
        'NfeInutilizacao': '/nfe2/services/NFeInutilizacao4',
        'NfeConsultaProtocolo': '/nfe2/services/NFeConsultaProtocolo4',
        'NfeStatusServico': '/nfe2/services/NFeStatusServico4',
        'NfeConsultaCadastro': '/nfe2/services/CadConsultaCadastro4',
        'RecepcaoEvento': '/nfe2/services/NFeRecepcaoEvento4',
        'NFeAutorizacao': '/nfe2/services/NFeAutorizacao4',
        'NFeRetAutorizacao': '/nfe2/services/NFeRetAutorizacao4',
    },
    'MS': {
        'prod_server': 'hom.nfe.sefaz.ms.gov.br',
        'dev_server': 'hom.nfe.sefaz.ms.gov.br',
        'NfeInutilizacao': '/ws/NFeInutilizacao4',
        'NfeConsultaProtocolo': '/ws/NFeConsultaProtocolo4',
        'NfeStatusServico': '/ws/NFeStatusServico4',
        'NfeConsultaCadastro': '/ws/CadConsultaCadastro4',
        'RecepcaoEvento': '/ws/NFeRecepcaoEvento4',
        'NFeAutorizacao': '/ws/NFeAutorizacao4',
        'NFeRetAutorizacao': '/ws/NFeRetAutorizacao4',
    },
    'MT': {
        'prod_server': 'homologacao.sefaz.mt.gov.br',
        'dev_server': 'homologacao.sefaz.mt.gov.br',
        'NfeInutilizacao': '/nfews/v2/services/NfeInutilizacao4?wsdl',
        'NfeConsultaProtocolo': '/nfews/v2/services/NfeConsulta4?wsdl',
        'NfeStatusServico': '/nfews/v2/services/NfeStatusServico4?wsdl',
        'NfeConsultaCadastro': '/nfews/v2/services/CadConsultaCadastro4?wsdl',
        'RecepcaoEvento': '/nfews/v2/services/RecepcaoEvento4?wsdl',
        'NFeAutorizacao': '/nfews/v2/services/NfeAutorizacao4?wsdl',
        'NFeRetAutorizacao': '/nfews/v2/services/NfeRetAutorizacao4?wsdl',
    },
    'PE': {
        'prod_server': 'nfehomolog.sefaz.pe.gov.br',
        'dev_server': 'nfehomolog.sefaz.pe.gov.br',
        'NfeInutilizacao': '/nfe-service/services/NFeInutilizacao4?wsdl',
        'NfeConsultaProtocolo': '/nfe-service/services/NFeConsultaProtocolo4?wsdl',
        'NfeStatusServico': '/nfe-service/services/NFeStatusServico4?wsdl',
        'NfeConsultaCadastro': '/nfe-service/services/CadConsultaCadastro4?wsdl',
        'RecepcaoEvento': '/nfe-service/services/NFeRecepcaoEvento4?wsdl',
        'NFeAutorizacao': '/nfe-service/services/NFeAutorizacao4?wsdl',
        'NFeRetAutorizacao': '/nfe-service/services/NFeRetAutorizacao4?wsdl',
    },
    'PR': {
        'prod_server': 'homologacao.nfe.sefa.pr.gov.br',
        'dev_server': 'homologacao.nfe.sefa.pr.gov.br',
        'NfeInutilizacao': '/nfe/NFeInutilizacao4?wsdl',
        'NfeConsultaProtocolo': '/nfe/NFeConsultaProtocolo4?wsdl',
        'NfeStatusServico': '/nfe/NFeStatusServico4?wsdl',
        'NfeConsultaCadastro': '/nfe/CadConsultaCadastro4?wsdl',
        'RecepcaoEvento': '/nfe/NFeRecepcaoEvento4?wsdl',
        'NFeAutorizacao': '/nfe/NFeAutorizacao4?wsdl',
        'NFeRetAutorizacao': '/nfe/NFeRetAutorizacao4?wsdl',
    },
    'RS': {
        'prod_server': 'nfe-homologacao.sefazrs.rs.gov.br',
        'dev_server': 'nfe-homologacao.sefazrs.rs.gov.br',
        'NfeInutilizacao': '/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
        'NfeConsultaProtocolo': '/ws/NfeConsulta/NfeConsulta4.asmx',
        'NfeStatusServico': '/ws/NfeStatusServico/NfeStatusServico4.asmx',
        'NfeConsultaCadastro': '/ws/cadconsultacadastro/cadconsultacadastro4.asmx',
        'RecepcaoEvento': '/ws/recepcaoevento/recepcaoevento4.asmx',
        'NFeAutorizacao': '/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
        'NFeRetAutorizacao': '/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
    },
    'SP': {
        'prod_server': 'homologacao.nfe.fazenda.sp.gov.br',
        'dev_server': 'homologacao.nfe.fazenda.sp.gov.br',
        'NfeInutilizacao': '/ws/nfeinutilizacao4.asmx',
        'NfeConsultaProtocolo': '/ws/nfeconsultaprotocolo4.asmx',
        'NfeStatusServico': '/ws/nfestatusservico4.asmx',
        'NfeConsultaCadastro': '/ws/cadconsultacadastro4.asmx',
        'RecepcaoEvento': '/ws/nferecepcaoevento4.asmx',
        'NFeAutorizacao': '/ws/nfeautorizacao4.asmx',
        'NFeRetAutorizacao': '/ws/nferetautorizacao4.asmx',
    },
    'SVAN': {
        'prod_server': 'hom.sefazvirtual.fazenda.gov.br',
        'dev_server': 'hom.sefazvirtual.fazenda.gov.br',
        'NfeInutilizacao': '/NFeInutilizacao4/NFeInutilizacao4.asmx',
        'NfeConsultaProtocolo': '/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
        'NfeStatusServico': '/NFeStatusServico4/NFeStatusServico4.asmx',
        'RecepcaoEvento': '/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
        'NFeAutorizacao': '/NFeAutorizacao4/NFeAutorizacao4.asmx',
        'NFeRetAutorizacao': '/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
    },
    'SVRS': {
        'prod_server': 'nfe-homologacao.svrs.rs.gov.br',
        'dev_server': 'nfe-homologacao.svrs.rs.gov.br',
        'NfeInutilizacao': '/ws/nfeinutilizacao/nfeinutilizacao4.asmx',
        'NfeConsultaProtocolo': '/ws/NfeConsulta/NfeConsulta4.asmx',
        'NfeStatusServico': '/ws/NfeStatusServico/NfeStatusServico4.asmx',
        'NfeConsultaCadastro': '/ws/cadconsultacadastro/cadconsultacadastro4.asmx',
        'RecepcaoEvento': '/ws/recepcaoevento/recepcaoevento4.asmx',
        'NFeAutorizacao': '/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
        'NFeRetAutorizacao': '/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
    },
    'SVC-AN': {
        'prod_server': 'hom.sefazvirtual.fazenda.gov.br',
        'dev_server': 'hom.sefazvirtual.fazenda.gov.br',
        'NfeInutilizacao': '/NFeInutilizacao4/NFeInutilizacao4.asmx',
        'NfeConsultaProtocolo': '/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx',
        'NfeStatusServico': '/NFeStatusServico4/NFeStatusServico4.asmx',
        'RecepcaoEvento': '/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
        'NFeAutorizacao': '/NFeAutorizacao4/NFeAutorizacao4.asmx',
        'NFeRetAutorizacao': '/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx',
    },
    'SVC-RS': {
        'prod_server': 'nfe-homologacao.svrs.rs.gov.br',
        'dev_server': 'nfe-homologacao.svrs.rs.gov.br',
        'NfeConsultaProtocolo': '/ws/NfeConsulta/NfeConsulta4.asmx',
        'NfeStatusServico': '/ws/NfeStatusServico/NfeStatusServico4.asmx',
        'RecepcaoEvento': '/ws/recepcaoevento/recepcaoevento4.asmx',
        'NFeAutorizacao': '/ws/NfeAutorizacao/NFeAutorizacao4.asmx',
        'NFeRetAutorizacao': '/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx',
    },
    'AN': {
        'prod_server': 'hom1.nfe.fazenda.gov.br',
        'dev_server': 'hom1.nfe.fazenda.gov.br',
        'NFeDistribuicaoDFe': '/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx',
        'RecepcaoEvento': '/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx',
    },
}

