"""This file was generated by xsdata, v26.2, on 2026-09-25 12:39:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


class DetEventoDescEvento2(Enum):
    OPERACAO_NAO_REALIZADA = "Operacao nao Realizada"


class DetEventoVersao(Enum):
    VALUE_1_00 = "1.00"


@dataclass(kw_only=True)
class DetEvento:
    """
    Schema XML de validação do evento de Recusa de Recebimento (Operação
    não Realizada).

    :ivar descEvento: Descrição do Evento:"Operação não Realizada"
    :ivar xJust: Justificativa de recusa do recebimento da mercadoria
    :ivar versao:
    """

    class Meta:
        name = "detEvento"
        namespace = "http://www.portalfiscal.inf.br/nfe"

    descEvento: DetEventoDescEvento2 = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
        }
    )
    xJust: str = field(
        metadata={
            "type": "Element",
            "min_length": 15,
            "max_length": 255,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        }
    )
    versao: DetEventoVersao = field(
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
        }
    )
