"""This file was generated by xsdata, v25.7, on 2026-07-10 14:48:06

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.bpe.bindings.v1_0.cons_sit_bpe_tipos_basico_v1_00 import (
    TconsSitBpe,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/bpe"


@dataclass
class ConsSitBpe(TconsSitBpe):
    """
    Schema de validação XML dp Pedido de Consulta da Situação Atual do BP-e.
    """

    class Meta:
        name = "consSitBPe"
        namespace = "http://www.portalfiscal.inf.br/bpe"
