"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:20

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__NAMESPACE__ = "http://www.portalfiscal.inf.br/bpe"


class EvExcessoBagagemDescEvento(Enum):
    EXCESSO_BAGAGEM = "Excesso Bagagem"


@dataclass(kw_only=True)
class EvExcessoBagagem:
    """
    Schema XML de validação do evento de excesso de bagagem 110117.

    :ivar descEvento: Descrição do Evento - “Excesso Bagagem”
    :ivar nProt: Número do Protocolo de Status do BP-e.
    :ivar qBagagem: Quantidade de volumes de bagagem carregados
    :ivar vTotBag: Valor total do serviço Pode conter zeros quando o
        BP-e for de complemento de ICMS
    """

    class Meta:
        name = "evExcessoBagagem"
        namespace = "http://www.portalfiscal.inf.br/bpe"

    descEvento: None | EvExcessoBagagemDescEvento = field(
        default=None,
        metadata={
            "type": "Element",
            "white_space": "preserve",
        },
    )
    nProt: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "white_space": "preserve",
            "pattern": r"[0-9]{15}",
        },
    )
    qBagagem: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "min_length": 1,
            "max_length": 20,
            "white_space": "preserve",
        },
    )
    vTotBag: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
