"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:20

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.bpe.bindings.v1_0.evento_bpe_tipos_basico_v1_00 import Tevento

__NAMESPACE__ = "http://www.portalfiscal.inf.br/bpe"


@dataclass(kw_only=True)
class EventoBpe(Tevento):
    """
    Schema XML de validação do Pedido de Registro de Evento do BP-e.
    """

    class Meta:
        name = "eventoBPe"
        namespace = "http://www.portalfiscal.inf.br/bpe"
