"""This file was generated by xsdata, v24.2.1, on 2024-02-24 11:16:43

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass
from nfelib.bpe.bindings.v1_0.bpe_tipos_basico_v1_00 import TretBpe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/bpe"


@dataclass
class RetBpe(TretBpe):
    """
    Schema XML de validação do retorno do BP-e.
    """

    class Meta:
        name = "retBPe"
        namespace = "http://www.portalfiscal.inf.br/bpe"
