"""This file was generated by xsdata, v24.4, on 2024-05-08 08:25:46

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass

from nfelib.nfe_insucesso.bindings.v1_0.leiaute_evento_insucesso_nfe_v1_00 import (
    TenvEvento,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class EnvEvento(TenvEvento):
    """
    Schema XML de validação do lote de envio do evento de Insucesso na Entrega da
    NF-e.
    """

    class Meta:
        name = "envEvento"
        namespace = "http://www.portalfiscal.inf.br/nfe"
