"""This file was generated by xsdata, v25.7, on 2026-03-04 17:00:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import Optional

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe"


@dataclass
class CteDistDfeInteresse:
    class Meta:
        name = "cteDistDFeInteresse"
        namespace = (
            "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe"
        )

    cteDadosMsg: Optional["CteDistDfeInteresse.CteDadosMsg"] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class CteDadosMsg:
        content: list[object] = field(
            default_factory=list,
            metadata={
                "type": "Wildcard",
                "namespace": "##any",
                "mixed": True,
            },
        )


@dataclass
class CteDistDfeInteresseResponse:
    class Meta:
        name = "cteDistDFeInteresseResponse"
        namespace = (
            "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe"
        )

    cteDistDFeInteresseResult: Optional[
        "CteDistDfeInteresseResponse.CteDistDfeInteresseResult"
    ] = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )

    @dataclass
    class CteDistDfeInteresseResult:
        content: list[object] = field(
            default_factory=list,
            metadata={
                "type": "Wildcard",
                "namespace": "##any",
                "mixed": True,
            },
        )


@dataclass
class CteDistribuicaoDfeSoapCteDistDfeInteresseInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteDistribuicaoDfeSoapCteDistDfeInteresseInput.Body"] = (
        field(
            default=None,
            metadata={
                "name": "Body",
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body:
        cteDistDFeInteresse: Optional[CteDistDfeInteresse] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe",
            },
        )


@dataclass
class CteDistribuicaoDfeSoapCteDistDfeInteresseOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteDistribuicaoDfeSoapCteDistDfeInteresseOutput.Body"] = (
        field(
            default=None,
            metadata={
                "name": "Body",
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body:
        cteDistDFeInteresseResponse: Optional[CteDistDfeInteresseResponse] = (
            field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe",
                },
            )
        )
        fault: Optional[
            "CteDistribuicaoDfeSoapCteDistDfeInteresseOutput.Body.Fault"
        ] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            },
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )


class CteDistribuicaoDfeSoapCteDistDfeInteresse:
    style = "document"
    location = "https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx"
    transport = "http://schemas.xmlsoap.org/soap/http"
    soapAction = "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe/cteDistDFeInteresse"
    input = CteDistribuicaoDfeSoapCteDistDfeInteresseInput
    output = CteDistribuicaoDfeSoapCteDistDfeInteresseOutput
