"""This file was generated by xsdata, v25.4, on 2025-04-15 20:52:19

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import Optional

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4"


@dataclass
class CteDadosMsg:
    class Meta:
        name = "cteDadosMsg"
        namespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class CteRecepcaoGtveResult:
    class Meta:
        name = "cteRecepcaoGTVeResult"
        namespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class CteRecepcaoGtveV4Soap12CteRecepcaoGtveInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteRecepcaoGtveV4Soap12CteRecepcaoGtveInput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        },
    )

    @dataclass
    class Body:
        cteDadosMsg: Optional[CteDadosMsg] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4",
            },
        )


@dataclass
class CteRecepcaoGtveV4Soap12CteRecepcaoGtveOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteRecepcaoGtveV4Soap12CteRecepcaoGtveOutput.Body"] = (
        field(
            default=None,
            metadata={
                "name": "Body",
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body:
        cteRecepcaoGTVeResult: Optional[CteRecepcaoGtveResult] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4",
            },
        )
        fault: Optional[
            "CteRecepcaoGtveV4Soap12CteRecepcaoGtveOutput.Body.Fault"
        ] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            },
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )


class CteRecepcaoGtveV4Soap12CteRecepcaoGtve:
    style = "document"
    location = "https://cte.svrs.rs.gov.br/ws/CTeRecepcaoGTVeV4/CTeRecepcaoGTVeV4.asmx"
    transport = "http://schemas.xmlsoap.org/soap/http"
    soapAction = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4/cteRecepcaoGTVe"
    input = CteRecepcaoGtveV4Soap12CteRecepcaoGtveInput
    output = CteRecepcaoGtveV4Soap12CteRecepcaoGtveOutput
