"""This file was generated by xsdata, v25.4, on 2025-04-15 20:52:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import Optional

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoEventoV4"


@dataclass
class CteDadosMsg:
    class Meta:
        name = "cteDadosMsg"
        namespace = (
            "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoEventoV4"
        )

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class CteRecepcaoEventoResult:
    class Meta:
        name = "cteRecepcaoEventoResult"
        namespace = (
            "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoEventoV4"
        )

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class CteRecepcaoEventoV4Soap12CteRecepcaoEventoInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteRecepcaoEventoV4Soap12CteRecepcaoEventoInput.Body"] = (
        field(
            default=None,
            metadata={
                "name": "Body",
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body:
        cteDadosMsg: Optional[CteDadosMsg] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoEventoV4",
            },
        )


@dataclass
class CteRecepcaoEventoV4Soap12CteRecepcaoEventoOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteRecepcaoEventoV4Soap12CteRecepcaoEventoOutput.Body"] = (
        field(
            default=None,
            metadata={
                "name": "Body",
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body:
        cteRecepcaoEventoResult: Optional[CteRecepcaoEventoResult] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoEventoV4",
            },
        )
        fault: Optional[
            "CteRecepcaoEventoV4Soap12CteRecepcaoEventoOutput.Body.Fault"
        ] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            },
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )


class CteRecepcaoEventoV4Soap12CteRecepcaoEvento:
    style = "document"
    location = "https://cte.svrs.rs.gov.br/ws/CTeRecepcaoEventoV4/CTeRecepcaoEventoV4.asmx"
    transport = "http://schemas.xmlsoap.org/soap/http"
    soapAction = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoEventoV4/cteRecepcaoEvento"
    input = CteRecepcaoEventoV4Soap12CteRecepcaoEventoInput
    output = CteRecepcaoEventoV4Soap12CteRecepcaoEventoOutput
