"""This file was generated by xsdata, v25.4, on 2025-04-15 20:52:20

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass, field
from typing import Optional

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSimpV4"


@dataclass
class CteDadosMsg:
    class Meta:
        name = "cteDadosMsg"
        namespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSimpV4"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class CteRecepcaoSimpResult:
    class Meta:
        name = "cteRecepcaoSimpResult"
        namespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSimpV4"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )


@dataclass
class CteRecepcaoSimpV4Soap12CteRecepcaoSimpInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteRecepcaoSimpV4Soap12CteRecepcaoSimpInput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        },
    )

    @dataclass
    class Body:
        cteDadosMsg: Optional[CteDadosMsg] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSimpV4",
            },
        )


@dataclass
class CteRecepcaoSimpV4Soap12CteRecepcaoSimpOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CteRecepcaoSimpV4Soap12CteRecepcaoSimpOutput.Body"] = (
        field(
            default=None,
            metadata={
                "name": "Body",
                "type": "Element",
            },
        )
    )

    @dataclass
    class Body:
        cteRecepcaoSimpResult: Optional[CteRecepcaoSimpResult] = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSimpV4",
            },
        )
        fault: Optional[
            "CteRecepcaoSimpV4Soap12CteRecepcaoSimpOutput.Body.Fault"
        ] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            },
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                },
            )


class CteRecepcaoSimpV4Soap12CteRecepcaoSimp:
    style = "document"
    location = "https://cte.svrs.rs.gov.br/ws/CTeRecepcaoSimpV4/CTeRecepcaoSimpV4.asmx"
    transport = "http://schemas.xmlsoap.org/soap/http"
    soapAction = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSimpV4/cteRecepcaoSimp"
    input = CteRecepcaoSimpV4Soap12CteRecepcaoSimpInput
    output = CteRecepcaoSimpV4Soap12CteRecepcaoSimpOutput
