"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:15

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfe.bindings.v4_0.leiaute_cons_sit_nfe_v4_00 import TconsSitNfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass(kw_only=True)
class ConsSitNfe(TconsSitNfe):
    """
    Schema de validação XML dp Pedido de Consulta da Situação Atual da Nota
    Fiscal Eletrônica.
    """

    class Meta:
        name = "consSitNFe"
        namespace = "http://www.portalfiscal.inf.br/nfe"
