"""This file was generated by xsdata, v24.2.1, on 2024-02-24 11:31:20

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass
from nfelib.nfe.bindings.v4_0.leiaute_nfe_v4_00 import TenviNfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class EnviNfe(TenviNfe):
    """
    Schema XML de validação do Pedido de Concessão de Autorização da Nota Fiscal
    Eletrônica.
    """

    class Meta:
        name = "enviNFe"
        namespace = "http://www.portalfiscal.inf.br/nfe"
