"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:15

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfe.bindings.v4_0.leiaute_nfe_v4_00 import TnfeProc

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass(kw_only=True)
class NfeProc(TnfeProc):
    """
    NF-e processada.
    """

    class Meta:
        name = "nfeProc"
        namespace = "http://www.portalfiscal.inf.br/nfe"
