"""This file was generated by xsdata, v24.2.1, on 2024-02-24 11:31:20

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass
from nfelib.nfe.bindings.v4_0.leiaute_cons_sit_nfe_v4_00 import TretConsSitNfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class RetConsSitNfe(TretConsSitNfe):
    """
    Schema XML de validação do retorno da consulta da situação atual da NF-e.
    """

    class Meta:
        name = "retConsSitNFe"
        namespace = "http://www.portalfiscal.inf.br/nfe"
