"""This file was generated by xsdata, v24.11, on 2025-07-14 02:30:14

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.nfe.bindings.v4_0.leiaute_inut_nfe_v4_00 import TretInutNfe

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class RetInutNfe(TretInutNfe):
    """
    Schema XML de validação do retorno do Pedido de Inutilização de Numeração da
    Nota Fiscal Eletrônica.
    """

    class Meta:
        name = "retInutNFe"
        namespace = "http://www.portalfiscal.inf.br/nfe"
