"""This file was generated by xsdata, v24.11, on 2026-03-08 12:11:30

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.nfe_evento_generico.bindings.v1_0.leiaute_evento_v1_00 import (
    TenvEvento,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class EnvEvento(TenvEvento):
    """
    Schema XML de validação do lote de envio do Evento.
    """

    class Meta:
        name = "envEvento"
        namespace = "http://www.portalfiscal.inf.br/nfe"
