"""This file was generated by xsdata, v24.11, on 2026-03-08 12:11:30

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.nfe_evento_generico.bindings.v1_0.leiaute_evento_v1_00 import (
    TretEnvEvento,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class RetEnvEvento(TretEnvEvento):
    """
    Schema XML de Retorno da envio do Evento.
    """

    class Meta:
        name = "retEnvEvento"
        namespace = "http://www.portalfiscal.inf.br/nfe"
