"""This file was generated by xsdata, v24.11, on 2026-03-08 12:58:19

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.nfe_entrega.bindings.v1_0.leiaute_evento_entrega_nfe_v1_00 import (
    Tevento,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfe"


@dataclass
class Evento(Tevento):
    """
    Schema XML de validação do evento de comprovante de entrega da NF-e.
    """

    class Meta:
        name = "evento"
        namespace = "http://www.portalfiscal.inf.br/nfe"
