"""This file was generated by xsdata, v24.11, on 2026-03-08 12:59:48

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cte_tipos_basico_v4_00 import TcteSimp

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass
class CteSimp(TcteSimp):
    """
    Conhecimento de Transporte Eletrônico Simplificado.
    """

    class Meta:
        name = "CTeSimp"
        namespace = "http://www.portalfiscal.inf.br/cte"
