"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cte_tipos_basico_v4_00 import Tcte

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass(kw_only=True)
class Cte(Tcte):
    """
    Conhecimento de Transporte Eletrônico.
    """

    class Meta:
        name = "CTe"
        namespace = "http://www.portalfiscal.inf.br/cte"
