"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from xsdata.models.datatype import XmlPeriod

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass(kw_only=True)
class TajusteCompet:
    """
    Tipo Ajuste de Competência.

    :ivar competApur: Ano e mês referência do período de apuração (AAAA-
        MM)
    :ivar vIBS: Valor do IBS
    :ivar vCBS: Valor da CBS
    """

    class Meta:
        name = "TAjusteCompet"

    competApur: None | XmlPeriod = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "min_inclusive": XmlPeriod("2025-01"),
        },
    )
    vIBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    vCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class TcredPres:
    """
    Tipo Crédito Presumido.

    :ivar pCredPres: Percentual do Crédito Presumido
    :ivar vCredPres: Valor do Crédito Presumido
    :ivar vCredPresCondSus: Valor do Crédito Presumido Condição
        Suspensiva, preencher apenas para cCredPres que possui indicação
        de Condição Suspensiva
    """

    class Meta:
        name = "TCredPres"

    pCredPres: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vCredPres: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    vCredPresCondSus: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class TdevTrib:
    """
    Tipo Devolução Tributo.

    :ivar vDevTrib: Valor do tributo devolvido. No fornecimento de
        energia elétrica, água, esgoto e gás natural e em outras
        hipóteses definidas no regulamento
    """

    class Meta:
        name = "TDevTrib"

    vDevTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class Tdif:
    """
    Tipo Diferimento.

    :ivar pDif: Percentual do diferimento
    :ivar vDif: Valor do diferimento
    """

    class Meta:
        name = "TDif"

    pDif: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vDif: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


class TenteGov(Enum):
    """
    Tipo de Ente Governamental.
    """

    VALUE_1 = "1"
    VALUE_2 = "2"
    VALUE_3 = "3"
    VALUE_4 = "4"
    VALUE_5 = "5"
    VALUE_6 = "6"


@dataclass(kw_only=True)
class TestornoCred:
    """
    Tipo Estorno de Crédito.

    :ivar vIBSEstCred: Valor do IBS a ser estornado
    :ivar vCBSEstCred: Valor da CBS a ser estornada
    """

    class Meta:
        name = "TEstornoCred"

    vIBSEstCred: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    vCBSEstCred: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class TibscbsmonoTot:
    """
    Grupo de informações de totais da CBS/IBS com monofasia.

    :ivar vBCIBSCBS: Total Base de Calculo
    :ivar gIBS: Totalização do IBS
    :ivar gCBS: Totalização da CBS
    :ivar gMono: Totais da Monofasia Só deverá ser utilizado para DFe
        modelos 55 e 65
    :ivar gEstornoCred: Totalização do estorno de crédito
    """

    class Meta:
        name = "TIBSCBSMonoTot"

    vBCIBSCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    gIBS: None | TibscbsmonoTot.GIbs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gCBS: None | TibscbsmonoTot.GCbs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gMono: None | TibscbsmonoTot.GMono = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TibscbsmonoTot.GEstornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )

    @dataclass(kw_only=True)
    class GIbs:
        """
        :ivar gIBSUF: Totalização do IBS de competência da UF
        :ivar gIBSMun: Totalização do IBS de competência Municipal
        :ivar vIBS: Valor total do IBS
        :ivar vCredPres: Total do Crédito Presumido
        :ivar vCredPresCondSus: Total do Crédito Presumido Condição
            Suspensiva
        """

        gIBSUF: None | TibscbsmonoTot.GIbs.GIbsuf = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gIBSMun: None | TibscbsmonoTot.GIbs.GIbsmun = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        vIBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCredPres: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCredPresCondSus: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

        @dataclass(kw_only=True)
        class GIbsuf:
            """
            :ivar vDif: Total do Diferimento
            :ivar vDevTrib: Total de devoluções de tributos
            :ivar vIBSUF: Valor total do IBS Estadual
            """

            vDif: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vDevTrib: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vIBSUF: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )

        @dataclass(kw_only=True)
        class GIbsmun:
            """
            :ivar vDif: Total do Diferimento
            :ivar vDevTrib: Total de devoluções de tributos
            :ivar vIBSMun: Valor total do IBS Municipal
            """

            vDif: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vDevTrib: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vIBSMun: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )

    @dataclass(kw_only=True)
    class GCbs:
        """
        :ivar vDif: Total do Diferimento
        :ivar vDevTrib: Total de devoluções de tributos
        :ivar vCBS: Valor total da CBS
        :ivar vCredPres: Total do Crédito Presumido
        :ivar vCredPresCondSus: Total do Crédito Presumido Condição
            Suspensiva
        """

        vDif: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vDevTrib: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCredPres: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCredPresCondSus: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GMono:
        """
        :ivar vIBSMono: Valor total do IBS monofásico
        :ivar vCBSMono: Valor total da CBS monofásica
        :ivar vIBSMonoReten: Valor total do IBS monofásico sujeito a
            retenção
        :ivar vCBSMonoReten: Valor total da CBS monofásica sujeita a
            retenção
        :ivar vIBSMonoRet: Valor do IBS monofásico retido anteriormente
        :ivar vCBSMonoRet: Valor da CBS monofásica retida anteriormente
        """

        vIBSMono: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBSMono: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vIBSMonoReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBSMonoReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vIBSMonoRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBSMonoRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GEstornoCred:
        """
        :ivar vIBSEstCred: Valor total do IBS estornado
        :ivar vCBSEstCred: Valor total da CBS estornada
        """

        vIBSEstCred: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBSEstCred: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )


@dataclass(kw_only=True)
class Tibscbstot:
    """
    Grupo de informações de totais da CBS/IBS.

    :ivar vBCIBSCBS: Total Base de Calculo
    :ivar gIBS: Totalização do IBS
    :ivar gCBS: Totalização da CBS
    :ivar gEstornoCred: Totalização do estorno de crédito
    """

    class Meta:
        name = "TIBSCBSTot"

    vBCIBSCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    gIBS: None | Tibscbstot.GIbs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gCBS: None | Tibscbstot.GCbs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | Tibscbstot.GEstornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )

    @dataclass(kw_only=True)
    class GIbs:
        """
        :ivar gIBSUF: Totalização do IBS de competência da UF
        :ivar gIBSMun: Totalização do IBS de competência Municipal
        :ivar vIBS: Valor total do IBS
        """

        gIBSUF: None | Tibscbstot.GIbs.GIbsuf = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gIBSMun: None | Tibscbstot.GIbs.GIbsmun = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        vIBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

        @dataclass(kw_only=True)
        class GIbsuf:
            """
            :ivar vDif: Total do Diferimento
            :ivar vDevTrib: Total de devoluções de tributos
            :ivar vIBSUF: Valor total do IBS Estadual
            """

            vDif: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vDevTrib: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vIBSUF: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )

        @dataclass(kw_only=True)
        class GIbsmun:
            """
            :ivar vDif: Total do Diferimento
            :ivar vDevTrib: Total de devoluções de tributos
            :ivar vIBSMun: Valor total do IBS Municipal
            """

            vDif: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vDevTrib: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )
            vIBSMun: None | str = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "http://www.portalfiscal.inf.br/cte",
                    "white_space": "preserve",
                    "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
                },
            )

    @dataclass(kw_only=True)
    class GCbs:
        """
        :ivar vDif: Total do Diferimento
        :ivar vDevTrib: Total de devoluções de tributos
        :ivar vCBS: Valor total da CBS
        """

        vDif: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vDevTrib: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GEstornoCred:
        """
        :ivar vIBSEstCred: Valor total do IBS estornado
        :ivar vCBSEstCred: Valor total da CBS estornada
        """

        vIBSEstCred: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBSEstCred: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )


@dataclass(kw_only=True)
class Tis:
    """
    Grupo de informações do Imposto Seletivo.

    :ivar CSTIS: Código Situação Tributária do Imposto Seletivo
    :ivar cClassTribIS:
    :ivar vBCIS: Valor do BC
    :ivar pIS: Alíquota do Imposto Seletivo (percentual)
    :ivar pISEspec: Alíquota do Imposto Seletivo (por valor)
    :ivar uTrib: Unidade de medida apropriada especificada em Lei
        Ordinaria para fins de apuração do Imposto Seletivo
    :ivar qTrib: Quantidade com abse no campo uTrib informado
    :ivar vIS: Valor do Imposto Seletivo calculado
    """

    class Meta:
        name = "TIS"

    CSTIS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTribIS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    vBCIS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    pIS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    pISEspec: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    uTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "min_length": 1,
            "max_length": 6,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    qTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0\.[1-9]{1}[0-9]{3}|0\.[0-9]{3}[1-9]{1}|0\.[0-9]{2}[1-9]{1}[0-9]{1}|0\.[0-9]{1}[1-9]{1}[0-9]{2}|[1-9]{1}[0-9]{0,10}(\.[0-9]{4})?",
        },
    )
    vIS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class Tistot:
    """
    Grupo de informações de totais do Imposto Seletivo.

    :ivar vIS: Valor Total do Imposto Seletivo
    """

    class Meta:
        name = "TISTot"

    vIS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


class TindDoacao(Enum):
    """
    Tipo Indicador de Doação.
    """

    VALUE_1 = "1"


@dataclass(kw_only=True)
class Tmonofasia:
    """
    Tipo Monofasia.

    :ivar gMonoPadrao: Grupo de informações da Tributação Monofásica
        padrão
    :ivar gMonoReten: Grupo de informações da Tributação Monofásica
        sujeita a retenção
    :ivar gMonoRet: Grupo de informações da Tributação Monofásica retida
        anteriormente
    :ivar gMonoDif: Grupo de informações do diferimento da Tributação
        Monofásica
    :ivar vTotIBSMonoItem: Total de IBS monofásico do item
    :ivar vTotCBSMonoItem: Total da CBS monofásica do item
    """

    class Meta:
        name = "TMonofasia"

    gMonoPadrao: None | Tmonofasia.GMonoPadrao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gMonoReten: None | Tmonofasia.GMonoReten = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gMonoRet: None | Tmonofasia.GMonoRet = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gMonoDif: None | Tmonofasia.GMonoDif = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    vTotIBSMonoItem: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    vTotCBSMonoItem: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )

    @dataclass(kw_only=True)
    class GMonoPadrao:
        """
        :ivar qBCMono: Quantidade tributada na monofasia
        :ivar adRemIBS: Alíquota ad rem do IBS
        :ivar adRemCBS: Alíquota ad rem da CBS
        :ivar vIBSMono: Valor do IBS monofásico
        :ivar vCBSMono: Valor da CBS monofásica
        """

        qBCMono: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\.[0-9]{4})?",
            },
        )
        adRemIBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        adRemCBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vIBSMono: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        vCBSMono: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GMonoReten:
        """
        :ivar qBCMonoReten: Quantidade tributada sujeita a retenção.
        :ivar adRemIBSReten: Alíquota ad rem do IBS sujeito a retenção
        :ivar vIBSMonoReten: Valor do IBS monofásico sujeito a retenção
        :ivar adRemCBSReten: Alíquota ad rem da CBS sujeita a retenção
        :ivar vCBSMonoReten: Valor da CBS monofásica sujeita a retenção
        """

        qBCMonoReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\.[0-9]{4})?",
            },
        )
        adRemIBSReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vIBSMonoReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        adRemCBSReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vCBSMonoReten: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GMonoRet:
        """
        :ivar qBCMonoRet: Quantidade tributada retida anteriormente
        :ivar adRemIBSRet: Alíquota ad rem do IBS retido anteriormente
        :ivar vIBSMonoRet: Valor do IBS retido anteriormente
        :ivar adRemCBSRet: Alíquota ad rem da CBS retida anteriormente
        :ivar vCBSMonoRet: Valor da CBS retida anteriormente
        """

        qBCMonoRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{4}|[1-9]{1}[0-9]{0,10}(\.[0-9]{4})?",
            },
        )
        adRemIBSRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vIBSMonoRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        adRemCBSRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vCBSMonoRet: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GMonoDif:
        """
        :ivar pDifIBS: Percentual do diferimento do imposto monofásico
        :ivar vIBSMonoDif: Valor do IBS monofásico diferido
        :ivar pDifCBS: Percentual do diferimento do imposto monofásico
        :ivar vCBSMonoDif: Valor da CBS monofásica diferida
        """

        pDifIBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vIBSMonoDif: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )
        pDifCBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        vCBSMonoDif: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )


class ToperCompraGov(Enum):
    """
    Tipo da Operação com Ente Governamental.
    """

    VALUE_1 = "1"
    VALUE_2 = "2"
    VALUE_3 = "3"
    VALUE_4 = "4"


@dataclass(kw_only=True)
class TpagRef:
    """
    Tipo Pagamento que ocorre em DFe emitdo anteriormente Informado para
    abater as parcelas de antecipação de pagamento, conforme art. 10 §4.

    :ivar refDFe: Chave de acesso do documento fiscal de antecipação de
        pagamento Obs: esse DFe deverá ter o indAntecipacaoPgto marcado
        no grupo ide
    """

    class Meta:
        name = "TPagRef"

    refDFe: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "min_occurs": 1,
            "max_occurs": 99,
        },
    )


@dataclass(kw_only=True)
class TpagamentoRtc:
    """
    Tipo dados do pagamento para o sistema de arrecadação Cada DFe que
    utilizar deverá utilizar esses tipo no grupo ide.

    :ivar tpMeioPgto: (Meio de pagamento utilizado (ver IT DFe 2026.001)
    :ivar CNPJReceb: CNPJ do recebedor do pagamento Informar zeros não
        significativos
    :ivar CNPJBasePSP: CNPJ base da instituição financeira Informar
        zeros não significativos
    :ivar nPag: Número sequencial do pagamento
    :ivar idTransacao: ID específico da transação financeira conforme o
        meio de pagamento
    """

    class Meta:
        name = "TPagamentoRTC"

    tpMeioPgto: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"[0-9]{2}",
        },
    )
    CNPJReceb: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"[A-Z0-9]{12}[0-9]{2}",
        },
    )
    CNPJBasePSP: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"[A-Z0-9]{8}",
        },
    )
    nPag: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
            "pattern": r"[1-9]{1}[0-9]{0,1}|[1-8]{1}[0-9]{2}|[9]{1}[0-8]{1}[0-9]{1}|[9]{1}[9]{1}[0]{1}",
        },
    )
    idTransacao: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "min_length": 2,
            "max_length": 35,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )


@dataclass(kw_only=True)
class Tred:
    """
    Tipo Redução Base de Cálculo.

    :ivar pRedAliq: Percentual de redução de aliquota do cClassTrib
    :ivar pAliqEfet: Aliquota Efetiva que será aplicada a Base de
        Calculo (em percentual)
    """

    class Meta:
        name = "TRed"

    pRedAliq: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    pAliqEfet: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )


class TtpCredPresIbszfm(Enum):
    """
    Tipo de classificação do Crédito Presumido IBS ZFM.
    """

    VALUE_0 = "0"
    VALUE_1 = "1"
    VALUE_2 = "2"
    VALUE_3 = "3"
    VALUE_4 = "4"


@dataclass(kw_only=True)
class TtransfCred:
    """
    Tipo Transferência de Crédito.

    :ivar vIBS: Valor do IBS a ser transferido
    :ivar vCBS: Valor da CBS a ser transferida
    """

    class Meta:
        name = "TTransfCred"

    vIBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    vCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class TtribCompraGov:
    """
    Tipo Tributação Compra Governamental.

    :ivar pAliqIBSUF:
    :ivar vTribIBSUF: Valor que seria devido a UF, sem aplicação do Art.
        473. da LC 214/2025
    :ivar pAliqIBSMun:
    :ivar vTribIBSMun: Valor que seria devido ao município, sem
        aplicação do Art. 473. da LC 214/2025
    :ivar pAliqCBS:
    :ivar vTribCBS: Valor que seria devido a CBS, sem aplicação do Art.
        473. da LC 214/2025
    """

    class Meta:
        name = "TTribCompraGov"

    pAliqIBSUF: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vTribIBSUF: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    pAliqIBSMun: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vTribIBSMun: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    pAliqCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vTribCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class TtribRegular:
    """
    Tipo Tributação Regular.

    :ivar CSTReg: Código da Situação Tributária do IBS e CBS Informar
        qual seria o CST caso não cumprida a condição
        resolutória/suspensiva
    :ivar cClassTribReg: Informar qual seria o cClassTrib caso não
        cumprida a condição resolutória/suspensiva
    :ivar pAliqEfetRegIBSUF: Alíquota do IBS da UF Informar como seria a
        Alíquota caso não cumprida a condição resolutória/suspensiva
    :ivar vTribRegIBSUF: Valor do IBS da UF Informar como seria o valor
        do Tributo caso não cumprida a condição resolutória/suspensiva
    :ivar pAliqEfetRegIBSMun: Alíquota do IBS do Município Informar como
        seria a Alíquota caso não cumprida a condição
        resolutória/suspensiva
    :ivar vTribRegIBSMun: Valor do IBS do Município Informar como seria
        o valor do Tributo caso não cumprida a condição
        resolutória/suspensiva
    :ivar pAliqEfetRegCBS: Alíquota da CBS Informar como seria a
        Alíquota caso não cumprida a condição resolutória/suspensiva
    :ivar vTribRegCBS: Valor da CBS Informar como seria o valor do
        Tributo caso não cumprida a condição resolutória/suspensiva
    """

    class Meta:
        name = "TTribRegular"

    CSTReg: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTribReg: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    pAliqEfetRegIBSUF: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vTribRegIBSUF: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    pAliqEfetRegIBSMun: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vTribRegIBSMun: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    pAliqEfetRegCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    vTribRegCBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class Tcibs:
    """
    Tipo CBS IBS Completo.

    :ivar vBC: Valor do BC
    :ivar gIBSUF: Grupo de informações do IBS na UF
    :ivar gIBSMun: Grupo de Informações do IBS no Município
    :ivar vIBS: Valor do IBS
    :ivar gCBS: Grupo de Tributação da CBS
    :ivar gTribRegular: Grupo de informações da Tributação Regular.
        Informar como seria a tributação caso não cumprida a condição
        resolutória/suspensiva. Exemplo 1: Art. 442, §4. Operações com
        ZFM e ALC. Exemplo 2: Operações com suspensão do tributo.
    :ivar gTribCompraGov: Grupo de informações da composição do valor do
        IBS e da CBS em compras governamental
    """

    class Meta:
        name = "TCIBS"

    vBC: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    gIBSUF: None | Tcibs.GIbsuf = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSMun: None | Tcibs.GIbsmun = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    vIBS: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    gCBS: None | Tcibs.GCbs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gTribRegular: None | TtribRegular = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gTribCompraGov: None | TtribCompraGov = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )

    @dataclass(kw_only=True)
    class GCbs:
        """
        :ivar pCBS: Aliquota da CBS (em percentual)
        :ivar gDif: Grupo de campos do Diferimento
        :ivar gDevTrib: Grupo de Informações da devolução de tributos
        :ivar gRed: Grupo de campos da redução de aliquota
        :ivar vCBS: Valor da CBS
        """

        pCBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        gDif: None | Tdif = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gDevTrib: None | TdevTrib = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gRed: None | Tred = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        vCBS: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GIbsuf:
        """
        :ivar pIBSUF: Aliquota do IBS de competência das UF (em
            percentual)
        :ivar gDif: Grupo de campos do Diferimento
        :ivar gDevTrib: Grupo de Informações da devolução de tributos
        :ivar gRed: Grupo de campos da redução de aliquota
        :ivar vIBSUF: Valor do IBS de competência das UF
        """

        pIBSUF: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        gDif: None | Tdif = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gDevTrib: None | TdevTrib = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gRed: None | Tred = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        vIBSUF: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )

    @dataclass(kw_only=True)
    class GIbsmun:
        """
        :ivar pIBSMun: Aliquota do IBS Municipal (em percentual)
        :ivar gDif: Grupo de campos do Diferimento
        :ivar gDevTrib: Grupo de Informações da devolução de tributos
        :ivar gRed: Grupo de campos da redução de aliquota
        :ivar vIBSMun: Valor do IBS Municipal
        """

        pIBSMun: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
            },
        )
        gDif: None | Tdif = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gDevTrib: None | TdevTrib = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        gRed: None | Tred = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
            },
        )
        vIBSMun: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/cte",
                "white_space": "preserve",
                "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
            },
        )


@dataclass(kw_only=True)
class TcompraGov:
    """
    Tipo Compras Governamentais Cada DFe que utilizar deverá utilizar esses
    tipo no grupo ide.

    :ivar tpEnteGov: Para administração pública direta e suas autarquias
        e fundações: 1=União 2=Estados 3=Distrito Federal 4=Municípios
        5=Consórcio Público 6=Comitê Gestor do IBS
    :ivar pRedutor: Percentual de redução de aliquota em compra
        governamental
    :ivar tpOperGov: Tipo da operação com ente governamental: 1 –
        Fornecimento com pagamento posterior; 2 - Recebimento do
        pagamento com fornecimento já realizado; 3 – Fornecimento com
        pagamento já realizado; 4 – Recebimento do pagamento com
        fornecimento posterior;
    """

    class Meta:
        name = "TCompraGov"

    tpEnteGov: None | TenteGov = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    pRedutor: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    tpOperGov: None | ToperCompraGov = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TcompraGovReduzido:
    """
    Tipo Compras Governamentais Cada DFe que utilizar deverá utilizar esses
    tipo no grupo ide.

    :ivar tpEnteGov: Para administração pública direta e suas autarquias
        e fundações: 1=União 2=Estados 3=Distrito Federal 4=Municípios
        5=Consórcio Público 6=Comitê Gestor do IBS
    :ivar pRedutor: Percentual de redução de aliquota em compra
        governamental
    :ivar tpOperGov: Tipo da operação com ente governamental: 1 –
        Fornecimento com pagamento posterior; 2 - Recebimento do
        pagamento com fornecimento já realizado; 3 – Fornecimento com
        pagamento já realizado; 4 – Recebimento do pagamento com
        fornecimento posterior;
    :ivar refDFeAnt: Chave de acesso do documento fiscal anterior.
        Deverá ser informado para tpOperGov 2 e 3 e vedado para os tipos
        1 e 4. No caso do toOperGov 2 aceitará apenas uma chave
        referenciada, no tipo 3 poderá aceitar múltiplas chaves Obs: a
        chave de acesso deverá ser de um emitente com o mesmo CNPJ base
    """

    class Meta:
        name = "TCompraGovReduzido"

    tpEnteGov: None | TenteGov = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    pRedutor: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2,4}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2,4})?",
        },
    )
    tpOperGov: None | ToperCompraGov = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    refDFeAnt: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TcredPresIbszfm:
    """
    Tipo Informações do crédito presumido de IBS para fornecimentos a
    partir da ZFM.

    :ivar competApur: Ano e mês referência do período de apuração (AAAA-
        MM)
    :ivar tpCredPresIBSZFM: Classificação de acordo com o art. 450, §
        1º, da LC 214/25 para o cálculo do crédito presumido na ZFM 0 -
        Sem crédito presumido; 1 - Bens de consumo final (55%); 2 - Bens
        de capital (75%); 3 - Bens intermediários (90,25%); 4 - Bens de
        informática e outros definidos em legislação (100%). OBS:
        Percentuais definidos no art. 450, § 1º, da LC 214/25 para o
        cálculo do crédito presumido
    :ivar vCredPresIBSZFM: Valor do crédito presumido calculado sobre o
        saldo devedor apurado
    """

    class Meta:
        name = "TCredPresIBSZFM"

    competApur: None | XmlPeriod = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "min_inclusive": XmlPeriod("2025-01"),
        },
    )
    tpCredPresIBSZFM: None | TtpCredPresIbszfm = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    vCredPresIBSZFM: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )


@dataclass(kw_only=True)
class TcredPresOper:
    """
    Tipo Crédito Presumido da Operação.

    :ivar vBCCredPres: Valor da Base de Cálculo do Crédito Presumido da
        Operação
    :ivar cCredPres: Código de Classificação do Crédito Presumido do IBS
        e da CBS
    :ivar gIBSCredPres: Grupo de Informações do Crédito Presumido
        referente ao IBS, quando aproveitado pelo emitente do documento.
    :ivar gCBSCredPres: Grupo de Informações do Crédito Presumido
        referente a CBS, quando aproveitado pelo emitente do documento.
    """

    class Meta:
        name = "TCredPresOper"

    vBCCredPres: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?",
        },
    )
    cCredPres: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{2}",
        },
    )
    gIBSCredPres: None | TcredPres = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gCBSCredPres: None | TcredPres = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribBpe:
    """
    Grupo de informações da Tributação do BPe.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao:
    :ivar gIBSCBS:
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    """

    class Meta:
        name = "TTribBPe"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribCte:
    """
    Grupo de informações da Tributação do CTe.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao:
    :ivar gIBSCBS:
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    """

    class Meta:
        name = "TTribCTe"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribNf3E:
    """
    Grupo de informações da Tributação da NF3e.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao: Indica se a operação é de doação
    :ivar gIBSCBS:
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    """

    class Meta:
        name = "TTribNF3e"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribNfag:
    """
    Grupo de informações da Tributação da NFAg.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao:
    :ivar gIBSCBS:
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    """

    class Meta:
        name = "TTribNFAg"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribNfce:
    """
    Grupo de informações da Tributação da NFCe.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao: Indica se a operação é de doação
    :ivar gIBSCBS:
    :ivar gIBSCBSMono:
    """

    class Meta:
        name = "TTribNFCe"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBSMono: None | Tmonofasia = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribNfcom:
    """
    Grupo de informações da Tributação da NFCom.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao: Indica se a operação é de doação
    :ivar gIBSCBS:
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    """

    class Meta:
        name = "TTribNFCom"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribNfgas:
    """
    Grupo de informações da Tributação da NFGas.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao:
    :ivar gIBSCBS:
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    """

    class Meta:
        name = "TTribNFGas"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )


@dataclass(kw_only=True)
class TtribNfe:
    """
    Grupo de informações da Tributação da NFe.

    :ivar CST: Código Situação Tributária do IBS/CBS
    :ivar cClassTrib:
    :ivar indDoacao: Indica se a operação é de doação
    :ivar gIBSCBS:
    :ivar gIBSCBSMono: Informar essa opção da Choice para Monofasia (CST
        620)
    :ivar gTransfCred: Informar essa opção da Choice para o CST 800
    :ivar gAjusteCompet: Informar essa opção da Choice para o CST 811
    :ivar gEstornoCred: Informado conforme indicador no cClassTrib
    :ivar gCredPresOper: Crédito Presumido da Operação. Informado
        conforme indicador no cClassTrib.
    :ivar gCredPresIBSZFM: Classificação de acordo com o art. 450, § 1º,
        da LC 214/25 para o cálculo do crédito presumido na ZFM.
        Informado conforme indicador no cClassTrib.
    """

    class Meta:
        name = "TTribNFe"

    CST: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{3}",
        },
    )
    cClassTrib: None | str = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
            "white_space": "preserve",
            "pattern": r"\d{6}",
        },
    )
    indDoacao: None | TindDoacao = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBS: None | Tcibs = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gIBSCBSMono: None | Tmonofasia = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gTransfCred: None | TtransfCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gAjusteCompet: None | TajusteCompet = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gEstornoCred: None | TestornoCred = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gCredPresOper: None | TcredPresOper = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
    gCredPresIBSZFM: None | TcredPresIbszfm = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/cte",
        },
    )
