"""This file was generated by xsdata, v26.2, on 2026-09-25 13:35:03

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


class EvCancCecteDescEvento(Enum):
    CANCELAMENTO_DO_COMPROVANTE_DE_ENTREGA_DO_CT_E = (
        "Cancelamento do Comprovante de Entrega do CT-e"
    )


@dataclass
class EvCancCecte:
    """
    Schema XML de validação do evento cancelamento do comprovante de
    entrega eletrônico do CT-e 110181.

    :ivar descEvento: Descrição do Evento - “Cancelamento do Comprovante
        de Entrega do CT-e”
    :ivar nProt: Número do Protocolo de autorização do CT-e
    :ivar nProtCE: Número do Protocolo de autorização do evento a ser
        cancelado
    """

    class Meta:
        name = "evCancCECTe"
        namespace = "http://www.portalfiscal.inf.br/cte"

    descEvento: EvCancCecteDescEvento = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
        }
    )
    nProt: str = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
            "pattern": r"[0-9]{15}",
        }
    )
    nProtCE: str = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
            "pattern": r"[0-9]{15}",
        }
    )
