"""This file was generated by xsdata, v25.7, on 2026-07-13 02:25:54

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from nfelib.cte.bindings.v4_0.dfe_tipos_basicos_v1_00 import TpagamentoRtc

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


class EvVincPgtoDescEvento(Enum):
    VINCULA_O_DO_PAGAMENTO = "Vinculação do Pagamento"
    VINCULACAO_DO_PAGAMENTO = "Vinculacao do Pagamento"


@dataclass
class EvVincPgto:
    """Schema XML de validação do evento de vinculação da transação de pagamento com o DFe  - 110300"

    :ivar descEvento: Descrição do Evento - “Vinculação Pagamento”
    :ivar nProt: Número do Protocolo de autorização do DFe
    :ivar pgto: Vinuclação com o pagamento
    """

    class Meta:
        name = "evVincPgto"
        namespace = "http://www.portalfiscal.inf.br/cte"

    descEvento: Optional[EvVincPgtoDescEvento] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
            "white_space": "preserve",
        },
    )
    nProt: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[0-9]{15}",
        },
    )
    pgto: Optional[TpagamentoRtc] = field(
        default=None,
        metadata={
            "type": "Element",
            "required": True,
        },
    )
