"""This file was generated by xsdata, v24.11, on 2026-01-12 15:21:45

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cte_tipos_basico_v4_00 import Tgtve

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass
class Gtve(Tgtve):
    """
    Guia de Trasnsporte Eletrônica.
    """

    class Meta:
        name = "GTVe"
        namespace = "http://www.portalfiscal.inf.br/cte"
