"""This file was generated by xsdata, v24.11, on 2026-01-12 15:21:45

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cte_tipos_basico_v4_00 import TretCte

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass
class RetCte(TretCte):
    """
    Schema XML de validação do retorno do recibo de envio do CT-e (Modelo 57)
    """

    class Meta:
        name = "retCTe"
        namespace = "http://www.portalfiscal.inf.br/cte"
