"""This file was generated by xsdata, v24.11, on 2025-07-14 05:12:19

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cons_sit_cte_tipos_basico_v4_00 import (
    TretConsSitCte,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass
class RetConsSitCte(TretConsSitCte):
    """
    Schema XML de validação do retorno da consulta da situação atual do CT-e.
    """

    class Meta:
        name = "retConsSitCTe"
        namespace = "http://www.portalfiscal.inf.br/cte"
