"""This file was generated by xsdata, v25.7, on 2026-07-13 02:25:54

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cte_tipos_basico_v4_00 import TretCteSimp

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass
class RetCteSimp(TretCteSimp):
    """
    Schema XML de validação do retorno do recibo de envio do CT-e Simplificado
    (Modelo 57)
    """

    class Meta:
        name = "retCTeSimp"
        namespace = "http://www.portalfiscal.inf.br/cte"
