"""This file was generated by xsdata, v26.2, on 2026-07-10 15:54:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.cte.bindings.v4_0.cons_sit_cte_tipos_basico_v4_00 import (
    TretConsSitCte,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/cte"


@dataclass(kw_only=True)
class RetConsSitCte(TretConsSitCte):
    """
    Schema XML de validação do retorno da consulta da situação atual do
    CT-e.
    """

    class Meta:
        name = "retConsSitCTe"
        namespace = "http://www.portalfiscal.inf.br/cte"
