"""This file was generated by xsdata, v25.7, on 2026-10-09 00:45:08

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from nfelib.nfse.bindings.v1_01.tipos_simples_v1_01 import (
    TsregEspTrib,
    TssituacaoEmissaoNfse,
    TstipoAmbiente,
)

__NAMESPACE__ = "http://www.sped.fazenda.gov.br/nfse"


@dataclass
class TcenderContribuinteCnc:
    """

    "

    :ivar CEP: Código de endereçamento postal do estabelecimento do
        contribuinte
    :ivar nro: Número do estabelecimento no logradouro informado
    :ivar xCpl: Informação complementar para identificação do endereço
        do contribuinte
    """

    class Meta:
        name = "TCEnderContribuinteCNC"

    CEP: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[0-9]{8}",
        },
    )
    nro: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
            "min_length": 1,
            "max_length": 60,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    xCpl: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "min_length": 1,
            "max_length": 156,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )


@dataclass
class TcinfoContribuinteCnc:
    """
    Informações para cadastramento de novos contribuintes CNC.
    "

    :ivar CNPJ: Número do CNPJ
    :ivar CPF: Número do CPF
    :ivar IM: Número da inscrição municipal
    :ivar dInscricaoMunicipal: Data da Inscrição Municipal: Dia, mês e
        ano (AAAAMMDD)
    :ivar enderContribuinteCNC: Grupo de informações do endereço do
        contribuinte do CNC
    :ivar fone: Número do telefone do prestador: Preencher com o Código
        DDD + número do telefone. Nas operações com exterior é permitido
        informar o código do país + código da localidade + número do
        telefone)
    :ivar email: Endereço de e-mail para contato com o contribuinte
    :ivar regEspTribContribuinteCNC: Tipos de Regimes Especiais de
        Tributação: 0 - Nenhum; 1 - Ato Cooperado (Cooperativa); 2 -
        Estimativa; 3 - Microempresa Municipal; 4 - Notário ou
        Registrador; 5 - Profissional Autônomo; 6 - Sociedade de
        Profissionais;
    :ivar situacaoCadastroContribuinte: Identificação da situação do
        cadastro do contribuinte
    :ivar motivoSituacaoCadastroContribuinte: Motivo pelo qual o
        contribuinte se enquadra na situação informada
    :ivar situacaoEmissaoNFSE: Situação Emissão NFS-e: 0 - Não
        Habilitado; 1 - Habilitado;
    """

    class Meta:
        name = "TCInfoContribuinteCNC"

    CNPJ: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "max_length": 14,
            "white_space": "preserve",
            "pattern": r"[0-9]{14}",
        },
    )
    CPF: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "max_length": 11,
            "white_space": "preserve",
            "pattern": r"[0-9]{11}",
        },
    )
    IM: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "min_length": 1,
            "max_length": 15,
            "white_space": "preserve",
        },
    )
    dInscricaoMunicipal: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
            "white_space": "preserve",
            "pattern": r"(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))",
        },
    )
    enderContribuinteCNC: Optional[TcenderContribuinteCnc] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
        },
    )
    fone: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "white_space": "preserve",
            "pattern": r"[0-9]{6,20}",
        },
    )
    email: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "min_length": 1,
            "max_length": 80,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    regEspTribContribuinteCNC: Optional[TsregEspTrib] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
        },
    )
    situacaoCadastroContribuinte: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "min_length": 1,
            "max_length": 150,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    motivoSituacaoCadastroContribuinte: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "min_length": 1,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    situacaoEmissaoNFSE: Optional[TssituacaoEmissaoNfse] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
        },
    )


@dataclass
class TcinfCnc:
    """

    "

    :ivar tpAmb: Identificação do Ambiente: 1 - Produção; 2 -
        Homologação
    :ivar dhGeracaoArquivo: Data e hora da geração do arquivo CNC. Data
        e hora no formato UTC (Universal Coordinated Time): AAAA-MM-
        DDThh:mm:ssTZD
    :ivar verAplic: Versão do aplicativo que gerou Informações para
        cadastramento de novos contribuintes CNC
    :ivar contribuintesCnc:
    """

    class Meta:
        name = "TCInfCNC"

    tpAmb: Optional[TstipoAmbiente] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
        },
    )
    dhGeracaoArquivo: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
            "white_space": "preserve",
            "pattern": r"(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))",
        },
    )
    verAplic: Optional[str] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
            "min_length": 1,
            "max_length": 20,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        },
    )
    contribuintesCnc: Optional[TcinfCnc.ContribuintesCnc] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
        },
    )

    @dataclass
    class ContribuintesCnc:
        """

        "

        :ivar contribuinteCnc: Grupo de informações cadastramento de
            novos contribuintes CNC
        """

        contribuinteCnc: list[TcinfoContribuinteCnc] = field(
            default_factory=list,
            metadata={
                "type": "Element",
                "namespace": "http://www.sped.fazenda.gov.br/nfse",
                "min_occurs": 1,
            },
        )


@dataclass
class Tcnc:
    class Meta:
        name = "TCNC"

    infCNC: Optional[TcinfCnc] = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.sped.fazenda.gov.br/nfse",
            "required": True,
        },
    )
    versao: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "white_space": "preserve",
            "pattern": r"1\.00",
        },
    )
