name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit flake8 pytest xmldiff
      - run: bandit --recursive --skip B101,B314,B320,B405,B410 .
      - run: flake8 . --builtins=basestring,unicode --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pip install -e .
      - run: pytest .
